/*
 * generated by Xtext 2.10.0
 */
package org.xtext.tesis.gramatica.ide.contentassist.antlr;

import com.google.inject.Inject;
import java.util.Collection;
import java.util.HashMap;
import java.util.Map;
import org.antlr.runtime.RecognitionException;
import org.eclipse.xtext.AbstractElement;
import org.eclipse.xtext.ide.editor.contentassist.antlr.AbstractContentAssistParser;
import org.eclipse.xtext.ide.editor.contentassist.antlr.FollowElement;
import org.eclipse.xtext.ide.editor.contentassist.antlr.internal.AbstractInternalContentAssistParser;
import org.xtext.tesis.gramatica.ide.contentassist.antlr.internal.InternalGramaticaParser;
import org.xtext.tesis.gramatica.services.GramaticaGrammarAccess;

public class GramaticaParser extends AbstractContentAssistParser {

	@Inject
	private GramaticaGrammarAccess grammarAccess;

	private Map<AbstractElement, String> nameMappings;

	@Override
	protected InternalGramaticaParser createParser() {
		InternalGramaticaParser result = new InternalGramaticaParser(null);
		result.setGrammarAccess(grammarAccess);
		return result;
	}

	@Override
	protected String getRuleName(AbstractElement element) {
		if (nameMappings == null) {
			nameMappings = new HashMap<AbstractElement, String>() {
				private static final long serialVersionUID = 1L;
				{
					put(grammarAccess.getOracionAccess().getAlternatives(), "rule__Oracion__Alternatives");
					put(grammarAccess.getSimpleAccess().getAlternatives_0(), "rule__Simple__Alternatives_0");
					put(grammarAccess.getSimpleAccess().getAlternatives_7(), "rule__Simple__Alternatives_7");
					put(grammarAccess.getSimpleAccess().getAlternatives_8(), "rule__Simple__Alternatives_8");
					put(grammarAccess.getSimpleAccess().getAlternatives_9(), "rule__Simple__Alternatives_9");
					put(grammarAccess.getComplejaAccess().getAlternatives_7(), "rule__Compleja__Alternatives_7");
					put(grammarAccess.getComplejaAccess().getAlternatives_12(), "rule__Compleja__Alternatives_12");
					put(grammarAccess.getComplejaAccess().getAlternatives_13(), "rule__Compleja__Alternatives_13");
					put(grammarAccess.getComplejaAccess().getAlternatives_16(), "rule__Compleja__Alternatives_16");
					put(grammarAccess.getComplejaAccess().getAlternatives_17_0(), "rule__Compleja__Alternatives_17_0");
					put(grammarAccess.getComplejaAccess().getAlternatives_17_1(), "rule__Compleja__Alternatives_17_1");
					put(grammarAccess.getLiteralAccess().getAlternatives(), "rule__Literal__Alternatives");
					put(grammarAccess.getSimpleAccess().getGroup(), "rule__Simple__Group__0");
					put(grammarAccess.getComplejaAccess().getGroup(), "rule__Compleja__Group__0");
					put(grammarAccess.getComplejaAccess().getGroup_17(), "rule__Compleja__Group_17__0");
					put(grammarAccess.getAtributoAccess().getGroup(), "rule__Atributo__Group__0");
					put(grammarAccess.getGramaticaAccess().getOracionesAssignment(), "rule__Gramatica__OracionesAssignment");
					put(grammarAccess.getSimpleAccess().getAtributoAssignment_1(), "rule__Simple__AtributoAssignment_1");
					put(grammarAccess.getSimpleAccess().getContextoAssignment_4(), "rule__Simple__ContextoAssignment_4");
					put(grammarAccess.getSimpleAccess().getLiteralAssignment_9_0(), "rule__Simple__LiteralAssignment_9_0");
					put(grammarAccess.getSimpleAccess().getAtributoAssignment_9_1(), "rule__Simple__AtributoAssignment_9_1");
					put(grammarAccess.getComplejaAccess().getAtributoAssignment_1(), "rule__Compleja__AtributoAssignment_1");
					put(grammarAccess.getComplejaAccess().getContextoAssignment_4(), "rule__Compleja__ContextoAssignment_4");
					put(grammarAccess.getComplejaAccess().getAtributoAssignment_9(), "rule__Compleja__AtributoAssignment_9");
					put(grammarAccess.getComplejaAccess().getAtributoAssignment_11(), "rule__Compleja__AtributoAssignment_11");
					put(grammarAccess.getComplejaAccess().getLiteralAssignment_13_0(), "rule__Compleja__LiteralAssignment_13_0");
					put(grammarAccess.getComplejaAccess().getAtributoAssignment_13_1(), "rule__Compleja__AtributoAssignment_13_1");
					put(grammarAccess.getComplejaAccess().getLiteralAssignment_17_1_0(), "rule__Compleja__LiteralAssignment_17_1_0");
					put(grammarAccess.getComplejaAccess().getAtributoAssignment_17_1_1(), "rule__Compleja__AtributoAssignment_17_1_1");
					put(grammarAccess.getAtributoAccess().getNameAssignment_1(), "rule__Atributo__NameAssignment_1");
					put(grammarAccess.getClaseAccess().getNameAssignment(), "rule__Clase__NameAssignment");
				}
			};
		}
		return nameMappings.get(element);
	}

	@Override
	protected Collection<FollowElement> getFollowElements(AbstractInternalContentAssistParser parser) {
		try {
			InternalGramaticaParser typedParser = (InternalGramaticaParser) parser;
			typedParser.entryRuleGramatica();
			return typedParser.getFollowElements();
		} catch(RecognitionException ex) {
			throw new RuntimeException(ex);
		}
	}

	@Override
	protected String[] getInitialHiddenTokens() {
		return new String[] { "RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT" };
	}

	public GramaticaGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(GramaticaGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
