/*
 * generated by Xtext 2.10.0
 */
package org.xtext.tesis.gramatica.ide.contentassist.antlr;

import com.google.inject.Inject;
import java.util.Collection;
import java.util.HashMap;
import java.util.Map;
import org.antlr.runtime.RecognitionException;
import org.eclipse.xtext.AbstractElement;
import org.eclipse.xtext.ide.editor.contentassist.antlr.AbstractContentAssistParser;
import org.eclipse.xtext.ide.editor.contentassist.antlr.FollowElement;
import org.eclipse.xtext.ide.editor.contentassist.antlr.internal.AbstractInternalContentAssistParser;
import org.xtext.tesis.gramatica.ide.contentassist.antlr.internal.InternalGramaticaParser;
import org.xtext.tesis.gramatica.services.GramaticaGrammarAccess;

public class GramaticaParser extends AbstractContentAssistParser {

	@Inject
	private GramaticaGrammarAccess grammarAccess;

	private Map<AbstractElement, String> nameMappings;

	@Override
	protected InternalGramaticaParser createParser() {
		InternalGramaticaParser result = new InternalGramaticaParser(null);
		result.setGrammarAccess(grammarAccess);
		return result;
	}

	@Override
	protected String getRuleName(AbstractElement element) {
		if (nameMappings == null) {
			nameMappings = new HashMap<AbstractElement, String>() {
				private static final long serialVersionUID = 1L;
				{
					put(grammarAccess.getOracionAccess().getAlternatives(), "rule__Oracion__Alternatives");
					put(grammarAccess.getSimpleAccess().getAlternatives_6(), "rule__Simple__Alternatives_6");
					put(grammarAccess.getDeterminanteAccess().getDescripcionAlternatives_0(), "rule__Determinante__DescripcionAlternatives_0");
					put(grammarAccess.getObligacionDeberAccess().getDescripcionAlternatives_0(), "rule__ObligacionDeber__DescripcionAlternatives_0");
					put(grammarAccess.getOperacionAccess().getDescripcionAlternatives_0(), "rule__Operacion__DescripcionAlternatives_0");
					put(grammarAccess.getLiteralAccess().getAlternatives(), "rule__Literal__Alternatives");
					put(grammarAccess.getNexoAccess().getDescripcionAlternatives_0(), "rule__Nexo__DescripcionAlternatives_0");
					put(grammarAccess.getComplejaAccess().getAlternatives_5_4_2(), "rule__Compleja__Alternatives_5_4_2");
					put(grammarAccess.getComplejaAccess().getAlternatives_5_4_4_2(), "rule__Compleja__Alternatives_5_4_4_2");
					put(grammarAccess.getComplejaAccess().getAlternatives_7_1(), "rule__Compleja__Alternatives_7_1");
					put(grammarAccess.getConectorAccess().getDescripcionAlternatives_0(), "rule__Conector__DescripcionAlternatives_0");
					put(grammarAccess.getOperacionColeccionAccess().getDescripcionAlternatives_0(), "rule__OperacionColeccion__DescripcionAlternatives_0");
					put(grammarAccess.getDocumentoAccess().getGroup(), "rule__Documento__Group__0");
					put(grammarAccess.getSimpleAccess().getGroup(), "rule__Simple__Group__0");
					put(grammarAccess.getObligacionAccess().getGroup(), "rule__Obligacion__Group__0");
					put(grammarAccess.getCompuestaAccess().getGroup(), "rule__Compuesta__Group__0");
					put(grammarAccess.getCompuestaAccess().getGroup_2(), "rule__Compuesta__Group_2__0");
					put(grammarAccess.getComplejaAccess().getGroup(), "rule__Compleja__Group__0");
					put(grammarAccess.getComplejaAccess().getGroup_5(), "rule__Compleja__Group_5__0");
					put(grammarAccess.getComplejaAccess().getGroup_5_4(), "rule__Compleja__Group_5_4__0");
					put(grammarAccess.getComplejaAccess().getGroup_5_4_4(), "rule__Compleja__Group_5_4_4__0");
					put(grammarAccess.getComplejaAccess().getGroup_7(), "rule__Compleja__Group_7__0");
					put(grammarAccess.getDocumentoAccess().getPathModeloAssignment_0(), "rule__Documento__PathModeloAssignment_0");
					put(grammarAccess.getDocumentoAccess().getPathOclAssignment_1(), "rule__Documento__PathOclAssignment_1");
					put(grammarAccess.getDocumentoAccess().getOracionesAssignment_2(), "rule__Documento__OracionesAssignment_2");
					put(grammarAccess.getOracionAccess().getContenidoAssignment_0(), "rule__Oracion__ContenidoAssignment_0");
					put(grammarAccess.getOracionAccess().getContenidoAssignment_1(), "rule__Oracion__ContenidoAssignment_1");
					put(grammarAccess.getOracionAccess().getContenidoAssignment_2(), "rule__Oracion__ContenidoAssignment_2");
					put(grammarAccess.getSimpleAccess().getDeterminanteAssignment_0(), "rule__Simple__DeterminanteAssignment_0");
					put(grammarAccess.getSimpleAccess().getAtributoAssignment_1(), "rule__Simple__AtributoAssignment_1");
					put(grammarAccess.getSimpleAccess().getSintagmaAssignment_2(), "rule__Simple__SintagmaAssignment_2");
					put(grammarAccess.getSimpleAccess().getContextoAssignment_3(), "rule__Simple__ContextoAssignment_3");
					put(grammarAccess.getSimpleAccess().getObligacionAssignment_4(), "rule__Simple__ObligacionAssignment_4");
					put(grammarAccess.getSimpleAccess().getOperacionAssignment_5(), "rule__Simple__OperacionAssignment_5");
					put(grammarAccess.getSimpleAccess().getLiteralAssignment_6_0(), "rule__Simple__LiteralAssignment_6_0");
					put(grammarAccess.getSimpleAccess().getAtributoAssignment_6_1(), "rule__Simple__AtributoAssignment_6_1");
					put(grammarAccess.getSimpleAccess().getFinOracionAssignment_7(), "rule__Simple__FinOracionAssignment_7");
					put(grammarAccess.getDeterminanteAccess().getDescripcionAssignment(), "rule__Determinante__DescripcionAssignment");
					put(grammarAccess.getAtributoAccess().getNameAssignment(), "rule__Atributo__NameAssignment");
					put(grammarAccess.getSintagmaPreposicionalAccess().getDescripcionAssignment(), "rule__SintagmaPreposicional__DescripcionAssignment");
					put(grammarAccess.getObligacionAccess().getNegacionAssignment_0(), "rule__Obligacion__NegacionAssignment_0");
					put(grammarAccess.getObligacionAccess().getObligacionDeberAssignment_1(), "rule__Obligacion__ObligacionDeberAssignment_1");
					put(grammarAccess.getObligacionDeberAccess().getDescripcionAssignment(), "rule__ObligacionDeber__DescripcionAssignment");
					put(grammarAccess.getNegacionAccess().getDescripcionAssignment(), "rule__Negacion__DescripcionAssignment");
					put(grammarAccess.getOperacionAccess().getDescripcionAssignment(), "rule__Operacion__DescripcionAssignment");
					put(grammarAccess.getClaseAccess().getNameAssignment(), "rule__Clase__NameAssignment");
					put(grammarAccess.getCompuestaAccess().getSimpleInicialAssignment_1(), "rule__Compuesta__SimpleInicialAssignment_1");
					put(grammarAccess.getCompuestaAccess().getNexoAssignment_2_0(), "rule__Compuesta__NexoAssignment_2_0");
					put(grammarAccess.getCompuestaAccess().getSimpleFinalAssignment_2_1(), "rule__Compuesta__SimpleFinalAssignment_2_1");
					put(grammarAccess.getNexoAccess().getDescripcionAssignment(), "rule__Nexo__DescripcionAssignment");
					put(grammarAccess.getComplejaAccess().getDeterminanteAssignment_0(), "rule__Compleja__DeterminanteAssignment_0");
					put(grammarAccess.getComplejaAccess().getAtrAssignment_1(), "rule__Compleja__AtrAssignment_1");
					put(grammarAccess.getComplejaAccess().getSintagmaAssignment_2(), "rule__Compleja__SintagmaAssignment_2");
					put(grammarAccess.getComplejaAccess().getContextoAssignment_3(), "rule__Compleja__ContextoAssignment_3");
					put(grammarAccess.getComplejaAccess().getConectAssignment_4(), "rule__Compleja__ConectAssignment_4");
					put(grammarAccess.getComplejaAccess().getOperacionColeccionAssignment_5_0(), "rule__Compleja__OperacionColeccionAssignment_5_0");
					put(grammarAccess.getComplejaAccess().getDeterminante1Assignment_5_1(), "rule__Compleja__Determinante1Assignment_5_1");
					put(grammarAccess.getComplejaAccess().getClaseAssignment_5_2(), "rule__Compleja__ClaseAssignment_5_2");
					put(grammarAccess.getComplejaAccess().getConect1Assignment_5_3(), "rule__Compleja__Conect1Assignment_5_3");
					put(grammarAccess.getComplejaAccess().getAtr1Assignment_5_4_0(), "rule__Compleja__Atr1Assignment_5_4_0");
					put(grammarAccess.getComplejaAccess().getOpe3Assignment_5_4_1(), "rule__Compleja__Ope3Assignment_5_4_1");
					put(grammarAccess.getComplejaAccess().getLit1Assignment_5_4_2_0(), "rule__Compleja__Lit1Assignment_5_4_2_0");
					put(grammarAccess.getComplejaAccess().getAtr2Assignment_5_4_2_1(), "rule__Compleja__Atr2Assignment_5_4_2_1");
					put(grammarAccess.getComplejaAccess().getOpe4Assignment_5_4_3(), "rule__Compleja__Ope4Assignment_5_4_3");
					put(grammarAccess.getComplejaAccess().getAtr4Assignment_5_4_4_0(), "rule__Compleja__Atr4Assignment_5_4_4_0");
					put(grammarAccess.getComplejaAccess().getOpe5Assignment_5_4_4_1(), "rule__Compleja__Ope5Assignment_5_4_4_1");
					put(grammarAccess.getComplejaAccess().getLit2Assignment_5_4_4_2_0(), "rule__Compleja__Lit2Assignment_5_4_4_2_0");
					put(grammarAccess.getComplejaAccess().getAtr5Assignment_5_4_4_2_1(), "rule__Compleja__Atr5Assignment_5_4_4_2_1");
					put(grammarAccess.getComplejaAccess().getConec1Assignment_5_5(), "rule__Compleja__Conec1Assignment_5_5");
					put(grammarAccess.getComplejaAccess().getOpeColAssignment_6(), "rule__Compleja__OpeColAssignment_6");
					put(grammarAccess.getComplejaAccess().getOpe6Assignment_7_0(), "rule__Compleja__Ope6Assignment_7_0");
					put(grammarAccess.getComplejaAccess().getLit3Assignment_7_1_0(), "rule__Compleja__Lit3Assignment_7_1_0");
					put(grammarAccess.getComplejaAccess().getAtr3Assignment_7_1_1(), "rule__Compleja__Atr3Assignment_7_1_1");
					put(grammarAccess.getComplejaAccess().getFinOracionAssignment_8(), "rule__Compleja__FinOracionAssignment_8");
					put(grammarAccess.getConectorAccess().getDescripcionAssignment(), "rule__Conector__DescripcionAssignment");
					put(grammarAccess.getOperacionColeccionAccess().getDescripcionAssignment(), "rule__OperacionColeccion__DescripcionAssignment");
				}
			};
		}
		return nameMappings.get(element);
	}

	@Override
	protected Collection<FollowElement> getFollowElements(AbstractInternalContentAssistParser parser) {
		try {
			InternalGramaticaParser typedParser = (InternalGramaticaParser) parser;
			typedParser.entryRuleDocumento();
			return typedParser.getFollowElements();
		} catch(RecognitionException ex) {
			throw new RuntimeException(ex);
		}
	}

	@Override
	protected String[] getInitialHiddenTokens() {
		return new String[] { "RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT" };
	}

	public GramaticaGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(GramaticaGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
