/*
 * generated by Xtext 2.10.0-SNAPSHOT
 */
package org.xtext.tesina.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class LenguajeNaturalReducidoAntlrTokenFileProvider implements IAntlrTokenFileProvider {

	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
		return classLoader.getResourceAsStream("org/xtext/tesina/parser/antlr/internal/InternalLenguajeNaturalReducido.tokens");
	}
}
