/**
 * generated by Xtext 2.10.0-SNAPSHOT
 */
package org.xtext.tesina.lenguajeNaturalReducido.impl;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.xtext.tesina.lenguajeNaturalReducido.Composicion;
import org.xtext.tesina.lenguajeNaturalReducido.Contenido;
import org.xtext.tesina.lenguajeNaturalReducido.LenguajeNaturalReducidoPackage;
import org.xtext.tesina.lenguajeNaturalReducido.Nexo;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Composicion</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.tesina.lenguajeNaturalReducido.impl.ComposicionImpl#getNexo <em>Nexo</em>}</li>
 *   <li>{@link org.xtext.tesina.lenguajeNaturalReducido.impl.ComposicionImpl#getContenido <em>Contenido</em>}</li>
 * </ul>
 *
 * @generated
 */
public class ComposicionImpl extends MinimalEObjectImpl.Container implements Composicion
{
  /**
   * The cached value of the '{@link #getNexo() <em>Nexo</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getNexo()
   * @generated
   * @ordered
   */
  protected Nexo nexo;

  /**
   * The cached value of the '{@link #getContenido() <em>Contenido</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getContenido()
   * @generated
   * @ordered
   */
  protected Contenido contenido;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected ComposicionImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return LenguajeNaturalReducidoPackage.Literals.COMPOSICION;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public Nexo getNexo()
  {
    return nexo;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetNexo(Nexo newNexo, NotificationChain msgs)
  {
    Nexo oldNexo = nexo;
    nexo = newNexo;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, LenguajeNaturalReducidoPackage.COMPOSICION__NEXO, oldNexo, newNexo);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setNexo(Nexo newNexo)
  {
    if (newNexo != nexo)
    {
      NotificationChain msgs = null;
      if (nexo != null)
        msgs = ((InternalEObject)nexo).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - LenguajeNaturalReducidoPackage.COMPOSICION__NEXO, null, msgs);
      if (newNexo != null)
        msgs = ((InternalEObject)newNexo).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - LenguajeNaturalReducidoPackage.COMPOSICION__NEXO, null, msgs);
      msgs = basicSetNexo(newNexo, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, LenguajeNaturalReducidoPackage.COMPOSICION__NEXO, newNexo, newNexo));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public Contenido getContenido()
  {
    return contenido;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetContenido(Contenido newContenido, NotificationChain msgs)
  {
    Contenido oldContenido = contenido;
    contenido = newContenido;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, LenguajeNaturalReducidoPackage.COMPOSICION__CONTENIDO, oldContenido, newContenido);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setContenido(Contenido newContenido)
  {
    if (newContenido != contenido)
    {
      NotificationChain msgs = null;
      if (contenido != null)
        msgs = ((InternalEObject)contenido).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - LenguajeNaturalReducidoPackage.COMPOSICION__CONTENIDO, null, msgs);
      if (newContenido != null)
        msgs = ((InternalEObject)newContenido).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - LenguajeNaturalReducidoPackage.COMPOSICION__CONTENIDO, null, msgs);
      msgs = basicSetContenido(newContenido, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, LenguajeNaturalReducidoPackage.COMPOSICION__CONTENIDO, newContenido, newContenido));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case LenguajeNaturalReducidoPackage.COMPOSICION__NEXO:
        return basicSetNexo(null, msgs);
      case LenguajeNaturalReducidoPackage.COMPOSICION__CONTENIDO:
        return basicSetContenido(null, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case LenguajeNaturalReducidoPackage.COMPOSICION__NEXO:
        return getNexo();
      case LenguajeNaturalReducidoPackage.COMPOSICION__CONTENIDO:
        return getContenido();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case LenguajeNaturalReducidoPackage.COMPOSICION__NEXO:
        setNexo((Nexo)newValue);
        return;
      case LenguajeNaturalReducidoPackage.COMPOSICION__CONTENIDO:
        setContenido((Contenido)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case LenguajeNaturalReducidoPackage.COMPOSICION__NEXO:
        setNexo((Nexo)null);
        return;
      case LenguajeNaturalReducidoPackage.COMPOSICION__CONTENIDO:
        setContenido((Contenido)null);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case LenguajeNaturalReducidoPackage.COMPOSICION__NEXO:
        return nexo != null;
      case LenguajeNaturalReducidoPackage.COMPOSICION__CONTENIDO:
        return contenido != null;
    }
    return super.eIsSet(featureID);
  }

} //ComposicionImpl
