/**
 * generated by Xtext 2.10.0-SNAPSHOT
 */
package org.xtext.tesina.lenguajeNaturalReducido.impl;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.xtext.tesina.lenguajeNaturalReducido.Composicion;
import org.xtext.tesina.lenguajeNaturalReducido.Contenido;
import org.xtext.tesina.lenguajeNaturalReducido.LenguajeNaturalReducidoPackage;
import org.xtext.tesina.lenguajeNaturalReducido.Simple;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Contenido</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.tesina.lenguajeNaturalReducido.impl.ContenidoImpl#getCondicional <em>Condicional</em>}</li>
 *   <li>{@link org.xtext.tesina.lenguajeNaturalReducido.impl.ContenidoImpl#getSimple <em>Simple</em>}</li>
 *   <li>{@link org.xtext.tesina.lenguajeNaturalReducido.impl.ContenidoImpl#getComposicion <em>Composicion</em>}</li>
 * </ul>
 *
 * @generated
 */
public class ContenidoImpl extends MinimalEObjectImpl.Container implements Contenido
{
  /**
   * The default value of the '{@link #getCondicional() <em>Condicional</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getCondicional()
   * @generated
   * @ordered
   */
  protected static final String CONDICIONAL_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getCondicional() <em>Condicional</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getCondicional()
   * @generated
   * @ordered
   */
  protected String condicional = CONDICIONAL_EDEFAULT;

  /**
   * The cached value of the '{@link #getSimple() <em>Simple</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getSimple()
   * @generated
   * @ordered
   */
  protected Simple simple;

  /**
   * The cached value of the '{@link #getComposicion() <em>Composicion</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getComposicion()
   * @generated
   * @ordered
   */
  protected Composicion composicion;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected ContenidoImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return LenguajeNaturalReducidoPackage.Literals.CONTENIDO;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public String getCondicional()
  {
    return condicional;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setCondicional(String newCondicional)
  {
    String oldCondicional = condicional;
    condicional = newCondicional;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, LenguajeNaturalReducidoPackage.CONTENIDO__CONDICIONAL, oldCondicional, condicional));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public Simple getSimple()
  {
    return simple;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetSimple(Simple newSimple, NotificationChain msgs)
  {
    Simple oldSimple = simple;
    simple = newSimple;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, LenguajeNaturalReducidoPackage.CONTENIDO__SIMPLE, oldSimple, newSimple);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setSimple(Simple newSimple)
  {
    if (newSimple != simple)
    {
      NotificationChain msgs = null;
      if (simple != null)
        msgs = ((InternalEObject)simple).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - LenguajeNaturalReducidoPackage.CONTENIDO__SIMPLE, null, msgs);
      if (newSimple != null)
        msgs = ((InternalEObject)newSimple).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - LenguajeNaturalReducidoPackage.CONTENIDO__SIMPLE, null, msgs);
      msgs = basicSetSimple(newSimple, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, LenguajeNaturalReducidoPackage.CONTENIDO__SIMPLE, newSimple, newSimple));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public Composicion getComposicion()
  {
    return composicion;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetComposicion(Composicion newComposicion, NotificationChain msgs)
  {
    Composicion oldComposicion = composicion;
    composicion = newComposicion;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, LenguajeNaturalReducidoPackage.CONTENIDO__COMPOSICION, oldComposicion, newComposicion);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setComposicion(Composicion newComposicion)
  {
    if (newComposicion != composicion)
    {
      NotificationChain msgs = null;
      if (composicion != null)
        msgs = ((InternalEObject)composicion).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - LenguajeNaturalReducidoPackage.CONTENIDO__COMPOSICION, null, msgs);
      if (newComposicion != null)
        msgs = ((InternalEObject)newComposicion).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - LenguajeNaturalReducidoPackage.CONTENIDO__COMPOSICION, null, msgs);
      msgs = basicSetComposicion(newComposicion, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, LenguajeNaturalReducidoPackage.CONTENIDO__COMPOSICION, newComposicion, newComposicion));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case LenguajeNaturalReducidoPackage.CONTENIDO__SIMPLE:
        return basicSetSimple(null, msgs);
      case LenguajeNaturalReducidoPackage.CONTENIDO__COMPOSICION:
        return basicSetComposicion(null, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case LenguajeNaturalReducidoPackage.CONTENIDO__CONDICIONAL:
        return getCondicional();
      case LenguajeNaturalReducidoPackage.CONTENIDO__SIMPLE:
        return getSimple();
      case LenguajeNaturalReducidoPackage.CONTENIDO__COMPOSICION:
        return getComposicion();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case LenguajeNaturalReducidoPackage.CONTENIDO__CONDICIONAL:
        setCondicional((String)newValue);
        return;
      case LenguajeNaturalReducidoPackage.CONTENIDO__SIMPLE:
        setSimple((Simple)newValue);
        return;
      case LenguajeNaturalReducidoPackage.CONTENIDO__COMPOSICION:
        setComposicion((Composicion)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case LenguajeNaturalReducidoPackage.CONTENIDO__CONDICIONAL:
        setCondicional(CONDICIONAL_EDEFAULT);
        return;
      case LenguajeNaturalReducidoPackage.CONTENIDO__SIMPLE:
        setSimple((Simple)null);
        return;
      case LenguajeNaturalReducidoPackage.CONTENIDO__COMPOSICION:
        setComposicion((Composicion)null);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case LenguajeNaturalReducidoPackage.CONTENIDO__CONDICIONAL:
        return CONDICIONAL_EDEFAULT == null ? condicional != null : !CONDICIONAL_EDEFAULT.equals(condicional);
      case LenguajeNaturalReducidoPackage.CONTENIDO__SIMPLE:
        return simple != null;
      case LenguajeNaturalReducidoPackage.CONTENIDO__COMPOSICION:
        return composicion != null;
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuffer result = new StringBuffer(super.toString());
    result.append(" (condicional: ");
    result.append(condicional);
    result.append(')');
    return result.toString();
  }

} //ContenidoImpl
