/**
 * generated by Xtext 2.10.0-SNAPSHOT
 */
package org.xtext.tesina.lenguajeNaturalReducido.impl;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.ecore.EPackage;

import org.eclipse.emf.ecore.impl.EFactoryImpl;

import org.eclipse.emf.ecore.plugin.EcorePlugin;

import org.xtext.tesina.lenguajeNaturalReducido.*;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model <b>Factory</b>.
 * <!-- end-user-doc -->
 * @generated
 */
public class LenguajeNaturalReducidoFactoryImpl extends EFactoryImpl implements LenguajeNaturalReducidoFactory
{
  /**
   * Creates the default factory implementation.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public static LenguajeNaturalReducidoFactory init()
  {
    try
    {
      LenguajeNaturalReducidoFactory theLenguajeNaturalReducidoFactory = (LenguajeNaturalReducidoFactory)EPackage.Registry.INSTANCE.getEFactory(LenguajeNaturalReducidoPackage.eNS_URI);
      if (theLenguajeNaturalReducidoFactory != null)
      {
        return theLenguajeNaturalReducidoFactory;
      }
    }
    catch (Exception exception)
    {
      EcorePlugin.INSTANCE.log(exception);
    }
    return new LenguajeNaturalReducidoFactoryImpl();
  }

  /**
   * Creates an instance of the factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public LenguajeNaturalReducidoFactoryImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EObject create(EClass eClass)
  {
    switch (eClass.getClassifierID())
    {
      case LenguajeNaturalReducidoPackage.DOCUMENTO: return createDocumento();
      case LenguajeNaturalReducidoPackage.ORACION: return createOracion();
      case LenguajeNaturalReducidoPackage.CONTENIDO: return createContenido();
      case LenguajeNaturalReducidoPackage.SIMPLE: return createSimple();
      case LenguajeNaturalReducidoPackage.EXPRESION_DERECHA: return createExpresionDerecha();
      case LenguajeNaturalReducidoPackage.COMPOSICION: return createComposicion();
      case LenguajeNaturalReducidoPackage.NEXO: return createNexo();
      case LenguajeNaturalReducidoPackage.EXPRESION: return createExpresion();
      case LenguajeNaturalReducidoPackage.COMPARACION: return createComparacion();
      case LenguajeNaturalReducidoPackage.PROPIEDAD: return createPropiedad();
      case LenguajeNaturalReducidoPackage.ITERACION: return createIteracion();
      case LenguajeNaturalReducidoPackage.ATRIBUTO: return createAtributo();
      case LenguajeNaturalReducidoPackage.TERMINO: return createTermino();
      case LenguajeNaturalReducidoPackage.AFIRMACION: return createAfirmacion();
      case LenguajeNaturalReducidoPackage.OPERACION: return createOperacion();
      case LenguajeNaturalReducidoPackage.LITERAL: return createLiteral();
      default:
        throw new IllegalArgumentException("The class '" + eClass.getName() + "' is not a valid classifier");
    }
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public Documento createDocumento()
  {
    DocumentoImpl documento = new DocumentoImpl();
    return documento;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public Oracion createOracion()
  {
    OracionImpl oracion = new OracionImpl();
    return oracion;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public Contenido createContenido()
  {
    ContenidoImpl contenido = new ContenidoImpl();
    return contenido;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public Simple createSimple()
  {
    SimpleImpl simple = new SimpleImpl();
    return simple;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public ExpresionDerecha createExpresionDerecha()
  {
    ExpresionDerechaImpl expresionDerecha = new ExpresionDerechaImpl();
    return expresionDerecha;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public Composicion createComposicion()
  {
    ComposicionImpl composicion = new ComposicionImpl();
    return composicion;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public Nexo createNexo()
  {
    NexoImpl nexo = new NexoImpl();
    return nexo;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public Expresion createExpresion()
  {
    ExpresionImpl expresion = new ExpresionImpl();
    return expresion;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public Comparacion createComparacion()
  {
    ComparacionImpl comparacion = new ComparacionImpl();
    return comparacion;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public Propiedad createPropiedad()
  {
    PropiedadImpl propiedad = new PropiedadImpl();
    return propiedad;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public Iteracion createIteracion()
  {
    IteracionImpl iteracion = new IteracionImpl();
    return iteracion;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public Atributo createAtributo()
  {
    AtributoImpl atributo = new AtributoImpl();
    return atributo;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public Termino createTermino()
  {
    TerminoImpl termino = new TerminoImpl();
    return termino;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public Afirmacion createAfirmacion()
  {
    AfirmacionImpl afirmacion = new AfirmacionImpl();
    return afirmacion;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public Operacion createOperacion()
  {
    OperacionImpl operacion = new OperacionImpl();
    return operacion;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public Literal createLiteral()
  {
    LiteralImpl literal = new LiteralImpl();
    return literal;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public LenguajeNaturalReducidoPackage getLenguajeNaturalReducidoPackage()
  {
    return (LenguajeNaturalReducidoPackage)getEPackage();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @deprecated
   * @generated
   */
  @Deprecated
  public static LenguajeNaturalReducidoPackage getPackage()
  {
    return LenguajeNaturalReducidoPackage.eINSTANCE;
  }

} //LenguajeNaturalReducidoFactoryImpl
