/**
 * generated by Xtext 2.10.0-SNAPSHOT
 */
package org.xtext.example.lenguajenaturalreducido.lenguajeNaturalReducido;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see org.xtext.example.lenguajenaturalreducido.lenguajeNaturalReducido.LenguajeNaturalReducidoFactory
 * @model kind="package"
 * @generated
 */
public interface LenguajeNaturalReducidoPackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "lenguajeNaturalReducido";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.xtext.org/example/lenguajenaturalreducido/LenguajeNaturalReducido";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "lenguajeNaturalReducido";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  LenguajeNaturalReducidoPackage eINSTANCE = org.xtext.example.lenguajenaturalreducido.lenguajeNaturalReducido.impl.LenguajeNaturalReducidoPackageImpl.init();

  /**
   * The meta object id for the '{@link org.xtext.example.lenguajenaturalreducido.lenguajeNaturalReducido.impl.DocumentoImpl <em>Documento</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.lenguajenaturalreducido.lenguajeNaturalReducido.impl.DocumentoImpl
   * @see org.xtext.example.lenguajenaturalreducido.lenguajeNaturalReducido.impl.LenguajeNaturalReducidoPackageImpl#getDocumento()
   * @generated
   */
  int DOCUMENTO = 0;

  /**
   * The feature id for the '<em><b>Oraciones</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DOCUMENTO__ORACIONES = 0;

  /**
   * The number of structural features of the '<em>Documento</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DOCUMENTO_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.example.lenguajenaturalreducido.lenguajeNaturalReducido.impl.OracionImpl <em>Oracion</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.lenguajenaturalreducido.lenguajeNaturalReducido.impl.OracionImpl
   * @see org.xtext.example.lenguajenaturalreducido.lenguajeNaturalReducido.impl.LenguajeNaturalReducidoPackageImpl#getOracion()
   * @generated
   */
  int ORACION = 1;

  /**
   * The feature id for the '<em><b>Oracion</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ORACION__ORACION = 0;

  /**
   * The number of structural features of the '<em>Oracion</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ORACION_FEATURE_COUNT = 1;


  /**
   * Returns the meta object for class '{@link org.xtext.example.lenguajenaturalreducido.lenguajeNaturalReducido.Documento <em>Documento</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Documento</em>'.
   * @see org.xtext.example.lenguajenaturalreducido.lenguajeNaturalReducido.Documento
   * @generated
   */
  EClass getDocumento();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.lenguajenaturalreducido.lenguajeNaturalReducido.Documento#getOraciones <em>Oraciones</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Oraciones</em>'.
   * @see org.xtext.example.lenguajenaturalreducido.lenguajeNaturalReducido.Documento#getOraciones()
   * @see #getDocumento()
   * @generated
   */
  EReference getDocumento_Oraciones();

  /**
   * Returns the meta object for class '{@link org.xtext.example.lenguajenaturalreducido.lenguajeNaturalReducido.Oracion <em>Oracion</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Oracion</em>'.
   * @see org.xtext.example.lenguajenaturalreducido.lenguajeNaturalReducido.Oracion
   * @generated
   */
  EClass getOracion();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.lenguajenaturalreducido.lenguajeNaturalReducido.Oracion#getOracion <em>Oracion</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Oracion</em>'.
   * @see org.xtext.example.lenguajenaturalreducido.lenguajeNaturalReducido.Oracion#getOracion()
   * @see #getOracion()
   * @generated
   */
  EAttribute getOracion_Oracion();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  LenguajeNaturalReducidoFactory getLenguajeNaturalReducidoFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link org.xtext.example.lenguajenaturalreducido.lenguajeNaturalReducido.impl.DocumentoImpl <em>Documento</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.lenguajenaturalreducido.lenguajeNaturalReducido.impl.DocumentoImpl
     * @see org.xtext.example.lenguajenaturalreducido.lenguajeNaturalReducido.impl.LenguajeNaturalReducidoPackageImpl#getDocumento()
     * @generated
     */
    EClass DOCUMENTO = eINSTANCE.getDocumento();

    /**
     * The meta object literal for the '<em><b>Oraciones</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference DOCUMENTO__ORACIONES = eINSTANCE.getDocumento_Oraciones();

    /**
     * The meta object literal for the '{@link org.xtext.example.lenguajenaturalreducido.lenguajeNaturalReducido.impl.OracionImpl <em>Oracion</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.lenguajenaturalreducido.lenguajeNaturalReducido.impl.OracionImpl
     * @see org.xtext.example.lenguajenaturalreducido.lenguajeNaturalReducido.impl.LenguajeNaturalReducidoPackageImpl#getOracion()
     * @generated
     */
    EClass ORACION = eINSTANCE.getOracion();

    /**
     * The meta object literal for the '<em><b>Oracion</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ORACION__ORACION = eINSTANCE.getOracion_Oracion();

  }

} //LenguajeNaturalReducidoPackage
