/*
 * generated by Xtext 2.10.0-SNAPSHOT
 */
package org.xtext.example.lenguajenaturalreducido


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class LenguajeNaturalReducidoStandaloneSetup extends LenguajeNaturalReducidoStandaloneSetupGenerated {

	def static void doSetup() {
		new LenguajeNaturalReducidoStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
