/**
 * generated by Xtext 2.10.0-SNAPSHOT
 */
package org.xtext.tesis.gramatica.gramatica.impl;

import org.eclipse.emf.common.notify.Notification;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.xtext.tesis.gramatica.gramatica.Atributo;
import org.xtext.tesis.gramatica.gramatica.GramaticaPackage;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Atributo</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.tesis.gramatica.gramatica.impl.AtributoImpl#getDeterminante <em>Determinante</em>}</li>
 *   <li>{@link org.xtext.tesis.gramatica.gramatica.impl.AtributoImpl#getPrefijo <em>Prefijo</em>}</li>
 *   <li>{@link org.xtext.tesis.gramatica.gramatica.impl.AtributoImpl#getNombre <em>Nombre</em>}</li>
 *   <li>{@link org.xtext.tesis.gramatica.gramatica.impl.AtributoImpl#getEnlace <em>Enlace</em>}</li>
 * </ul>
 *
 * @generated
 */
public class AtributoImpl extends MinimalEObjectImpl.Container implements Atributo
{
  /**
   * The default value of the '{@link #getDeterminante() <em>Determinante</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getDeterminante()
   * @generated
   * @ordered
   */
  protected static final String DETERMINANTE_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getDeterminante() <em>Determinante</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getDeterminante()
   * @generated
   * @ordered
   */
  protected String determinante = DETERMINANTE_EDEFAULT;

  /**
   * The default value of the '{@link #getPrefijo() <em>Prefijo</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getPrefijo()
   * @generated
   * @ordered
   */
  protected static final String PREFIJO_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getPrefijo() <em>Prefijo</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getPrefijo()
   * @generated
   * @ordered
   */
  protected String prefijo = PREFIJO_EDEFAULT;

  /**
   * The default value of the '{@link #getNombre() <em>Nombre</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getNombre()
   * @generated
   * @ordered
   */
  protected static final String NOMBRE_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getNombre() <em>Nombre</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getNombre()
   * @generated
   * @ordered
   */
  protected String nombre = NOMBRE_EDEFAULT;

  /**
   * The default value of the '{@link #getEnlace() <em>Enlace</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getEnlace()
   * @generated
   * @ordered
   */
  protected static final String ENLACE_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getEnlace() <em>Enlace</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getEnlace()
   * @generated
   * @ordered
   */
  protected String enlace = ENLACE_EDEFAULT;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected AtributoImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return GramaticaPackage.Literals.ATRIBUTO;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public String getDeterminante()
  {
    return determinante;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setDeterminante(String newDeterminante)
  {
    String oldDeterminante = determinante;
    determinante = newDeterminante;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, GramaticaPackage.ATRIBUTO__DETERMINANTE, oldDeterminante, determinante));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public String getPrefijo()
  {
    return prefijo;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setPrefijo(String newPrefijo)
  {
    String oldPrefijo = prefijo;
    prefijo = newPrefijo;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, GramaticaPackage.ATRIBUTO__PREFIJO, oldPrefijo, prefijo));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public String getNombre()
  {
    return nombre;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setNombre(String newNombre)
  {
    String oldNombre = nombre;
    nombre = newNombre;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, GramaticaPackage.ATRIBUTO__NOMBRE, oldNombre, nombre));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public String getEnlace()
  {
    return enlace;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setEnlace(String newEnlace)
  {
    String oldEnlace = enlace;
    enlace = newEnlace;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, GramaticaPackage.ATRIBUTO__ENLACE, oldEnlace, enlace));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case GramaticaPackage.ATRIBUTO__DETERMINANTE:
        return getDeterminante();
      case GramaticaPackage.ATRIBUTO__PREFIJO:
        return getPrefijo();
      case GramaticaPackage.ATRIBUTO__NOMBRE:
        return getNombre();
      case GramaticaPackage.ATRIBUTO__ENLACE:
        return getEnlace();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case GramaticaPackage.ATRIBUTO__DETERMINANTE:
        setDeterminante((String)newValue);
        return;
      case GramaticaPackage.ATRIBUTO__PREFIJO:
        setPrefijo((String)newValue);
        return;
      case GramaticaPackage.ATRIBUTO__NOMBRE:
        setNombre((String)newValue);
        return;
      case GramaticaPackage.ATRIBUTO__ENLACE:
        setEnlace((String)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case GramaticaPackage.ATRIBUTO__DETERMINANTE:
        setDeterminante(DETERMINANTE_EDEFAULT);
        return;
      case GramaticaPackage.ATRIBUTO__PREFIJO:
        setPrefijo(PREFIJO_EDEFAULT);
        return;
      case GramaticaPackage.ATRIBUTO__NOMBRE:
        setNombre(NOMBRE_EDEFAULT);
        return;
      case GramaticaPackage.ATRIBUTO__ENLACE:
        setEnlace(ENLACE_EDEFAULT);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case GramaticaPackage.ATRIBUTO__DETERMINANTE:
        return DETERMINANTE_EDEFAULT == null ? determinante != null : !DETERMINANTE_EDEFAULT.equals(determinante);
      case GramaticaPackage.ATRIBUTO__PREFIJO:
        return PREFIJO_EDEFAULT == null ? prefijo != null : !PREFIJO_EDEFAULT.equals(prefijo);
      case GramaticaPackage.ATRIBUTO__NOMBRE:
        return NOMBRE_EDEFAULT == null ? nombre != null : !NOMBRE_EDEFAULT.equals(nombre);
      case GramaticaPackage.ATRIBUTO__ENLACE:
        return ENLACE_EDEFAULT == null ? enlace != null : !ENLACE_EDEFAULT.equals(enlace);
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuffer result = new StringBuffer(super.toString());
    result.append(" (determinante: ");
    result.append(determinante);
    result.append(", prefijo: ");
    result.append(prefijo);
    result.append(", nombre: ");
    result.append(nombre);
    result.append(", enlace: ");
    result.append(enlace);
    result.append(')');
    return result.toString();
  }

} //AtributoImpl
