/**
 * generated by Xtext 2.10.0
 */
package org.xtext.tesis.gramatica.gramatica.impl;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.xtext.tesis.gramatica.gramatica.Compuesta;
import org.xtext.tesis.gramatica.gramatica.GramaticaPackage;
import org.xtext.tesis.gramatica.gramatica.Nexo;
import org.xtext.tesis.gramatica.gramatica.Simple;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Compuesta</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.tesis.gramatica.gramatica.impl.CompuestaImpl#getSimpleInicial <em>Simple Inicial</em>}</li>
 *   <li>{@link org.xtext.tesis.gramatica.gramatica.impl.CompuestaImpl#getNexo <em>Nexo</em>}</li>
 *   <li>{@link org.xtext.tesis.gramatica.gramatica.impl.CompuestaImpl#getSimpleFinal <em>Simple Final</em>}</li>
 * </ul>
 *
 * @generated
 */
public class CompuestaImpl extends MinimalEObjectImpl.Container implements Compuesta
{
  /**
   * The cached value of the '{@link #getSimpleInicial() <em>Simple Inicial</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getSimpleInicial()
   * @generated
   * @ordered
   */
  protected Simple simpleInicial;

  /**
   * The cached value of the '{@link #getNexo() <em>Nexo</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getNexo()
   * @generated
   * @ordered
   */
  protected Nexo nexo;

  /**
   * The cached value of the '{@link #getSimpleFinal() <em>Simple Final</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getSimpleFinal()
   * @generated
   * @ordered
   */
  protected Simple simpleFinal;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected CompuestaImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return GramaticaPackage.Literals.COMPUESTA;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public Simple getSimpleInicial()
  {
    return simpleInicial;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetSimpleInicial(Simple newSimpleInicial, NotificationChain msgs)
  {
    Simple oldSimpleInicial = simpleInicial;
    simpleInicial = newSimpleInicial;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, GramaticaPackage.COMPUESTA__SIMPLE_INICIAL, oldSimpleInicial, newSimpleInicial);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setSimpleInicial(Simple newSimpleInicial)
  {
    if (newSimpleInicial != simpleInicial)
    {
      NotificationChain msgs = null;
      if (simpleInicial != null)
        msgs = ((InternalEObject)simpleInicial).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - GramaticaPackage.COMPUESTA__SIMPLE_INICIAL, null, msgs);
      if (newSimpleInicial != null)
        msgs = ((InternalEObject)newSimpleInicial).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - GramaticaPackage.COMPUESTA__SIMPLE_INICIAL, null, msgs);
      msgs = basicSetSimpleInicial(newSimpleInicial, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, GramaticaPackage.COMPUESTA__SIMPLE_INICIAL, newSimpleInicial, newSimpleInicial));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public Nexo getNexo()
  {
    return nexo;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetNexo(Nexo newNexo, NotificationChain msgs)
  {
    Nexo oldNexo = nexo;
    nexo = newNexo;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, GramaticaPackage.COMPUESTA__NEXO, oldNexo, newNexo);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setNexo(Nexo newNexo)
  {
    if (newNexo != nexo)
    {
      NotificationChain msgs = null;
      if (nexo != null)
        msgs = ((InternalEObject)nexo).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - GramaticaPackage.COMPUESTA__NEXO, null, msgs);
      if (newNexo != null)
        msgs = ((InternalEObject)newNexo).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - GramaticaPackage.COMPUESTA__NEXO, null, msgs);
      msgs = basicSetNexo(newNexo, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, GramaticaPackage.COMPUESTA__NEXO, newNexo, newNexo));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public Simple getSimpleFinal()
  {
    return simpleFinal;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetSimpleFinal(Simple newSimpleFinal, NotificationChain msgs)
  {
    Simple oldSimpleFinal = simpleFinal;
    simpleFinal = newSimpleFinal;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, GramaticaPackage.COMPUESTA__SIMPLE_FINAL, oldSimpleFinal, newSimpleFinal);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setSimpleFinal(Simple newSimpleFinal)
  {
    if (newSimpleFinal != simpleFinal)
    {
      NotificationChain msgs = null;
      if (simpleFinal != null)
        msgs = ((InternalEObject)simpleFinal).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - GramaticaPackage.COMPUESTA__SIMPLE_FINAL, null, msgs);
      if (newSimpleFinal != null)
        msgs = ((InternalEObject)newSimpleFinal).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - GramaticaPackage.COMPUESTA__SIMPLE_FINAL, null, msgs);
      msgs = basicSetSimpleFinal(newSimpleFinal, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, GramaticaPackage.COMPUESTA__SIMPLE_FINAL, newSimpleFinal, newSimpleFinal));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case GramaticaPackage.COMPUESTA__SIMPLE_INICIAL:
        return basicSetSimpleInicial(null, msgs);
      case GramaticaPackage.COMPUESTA__NEXO:
        return basicSetNexo(null, msgs);
      case GramaticaPackage.COMPUESTA__SIMPLE_FINAL:
        return basicSetSimpleFinal(null, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case GramaticaPackage.COMPUESTA__SIMPLE_INICIAL:
        return getSimpleInicial();
      case GramaticaPackage.COMPUESTA__NEXO:
        return getNexo();
      case GramaticaPackage.COMPUESTA__SIMPLE_FINAL:
        return getSimpleFinal();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case GramaticaPackage.COMPUESTA__SIMPLE_INICIAL:
        setSimpleInicial((Simple)newValue);
        return;
      case GramaticaPackage.COMPUESTA__NEXO:
        setNexo((Nexo)newValue);
        return;
      case GramaticaPackage.COMPUESTA__SIMPLE_FINAL:
        setSimpleFinal((Simple)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case GramaticaPackage.COMPUESTA__SIMPLE_INICIAL:
        setSimpleInicial((Simple)null);
        return;
      case GramaticaPackage.COMPUESTA__NEXO:
        setNexo((Nexo)null);
        return;
      case GramaticaPackage.COMPUESTA__SIMPLE_FINAL:
        setSimpleFinal((Simple)null);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case GramaticaPackage.COMPUESTA__SIMPLE_INICIAL:
        return simpleInicial != null;
      case GramaticaPackage.COMPUESTA__NEXO:
        return nexo != null;
      case GramaticaPackage.COMPUESTA__SIMPLE_FINAL:
        return simpleFinal != null;
    }
    return super.eIsSet(featureID);
  }

} //CompuestaImpl
