/**
 * generated by Xtext 2.10.0
 */
package org.xtext.tesis.gramatica.gramatica.impl;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;

import org.xtext.tesis.gramatica.gramatica.Compuesta;
import org.xtext.tesis.gramatica.gramatica.GramaticaPackage;
import org.xtext.tesis.gramatica.gramatica.Nexo;
import org.xtext.tesis.gramatica.gramatica.Simple;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Compuesta</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.tesis.gramatica.gramatica.impl.CompuestaImpl#getSimple <em>Simple</em>}</li>
 *   <li>{@link org.xtext.tesis.gramatica.gramatica.impl.CompuestaImpl#getNexo <em>Nexo</em>}</li>
 * </ul>
 *
 * @generated
 */
public class CompuestaImpl extends OracionImpl implements Compuesta
{
  /**
   * The cached value of the '{@link #getSimple() <em>Simple</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getSimple()
   * @generated
   * @ordered
   */
  protected Simple simple;

  /**
   * The cached value of the '{@link #getNexo() <em>Nexo</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getNexo()
   * @generated
   * @ordered
   */
  protected Nexo nexo;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected CompuestaImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return GramaticaPackage.Literals.COMPUESTA;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public Simple getSimple()
  {
    return simple;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetSimple(Simple newSimple, NotificationChain msgs)
  {
    Simple oldSimple = simple;
    simple = newSimple;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, GramaticaPackage.COMPUESTA__SIMPLE, oldSimple, newSimple);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setSimple(Simple newSimple)
  {
    if (newSimple != simple)
    {
      NotificationChain msgs = null;
      if (simple != null)
        msgs = ((InternalEObject)simple).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - GramaticaPackage.COMPUESTA__SIMPLE, null, msgs);
      if (newSimple != null)
        msgs = ((InternalEObject)newSimple).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - GramaticaPackage.COMPUESTA__SIMPLE, null, msgs);
      msgs = basicSetSimple(newSimple, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, GramaticaPackage.COMPUESTA__SIMPLE, newSimple, newSimple));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public Nexo getNexo()
  {
    return nexo;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetNexo(Nexo newNexo, NotificationChain msgs)
  {
    Nexo oldNexo = nexo;
    nexo = newNexo;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, GramaticaPackage.COMPUESTA__NEXO, oldNexo, newNexo);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setNexo(Nexo newNexo)
  {
    if (newNexo != nexo)
    {
      NotificationChain msgs = null;
      if (nexo != null)
        msgs = ((InternalEObject)nexo).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - GramaticaPackage.COMPUESTA__NEXO, null, msgs);
      if (newNexo != null)
        msgs = ((InternalEObject)newNexo).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - GramaticaPackage.COMPUESTA__NEXO, null, msgs);
      msgs = basicSetNexo(newNexo, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, GramaticaPackage.COMPUESTA__NEXO, newNexo, newNexo));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case GramaticaPackage.COMPUESTA__SIMPLE:
        return basicSetSimple(null, msgs);
      case GramaticaPackage.COMPUESTA__NEXO:
        return basicSetNexo(null, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case GramaticaPackage.COMPUESTA__SIMPLE:
        return getSimple();
      case GramaticaPackage.COMPUESTA__NEXO:
        return getNexo();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case GramaticaPackage.COMPUESTA__SIMPLE:
        setSimple((Simple)newValue);
        return;
      case GramaticaPackage.COMPUESTA__NEXO:
        setNexo((Nexo)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case GramaticaPackage.COMPUESTA__SIMPLE:
        setSimple((Simple)null);
        return;
      case GramaticaPackage.COMPUESTA__NEXO:
        setNexo((Nexo)null);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case GramaticaPackage.COMPUESTA__SIMPLE:
        return simple != null;
      case GramaticaPackage.COMPUESTA__NEXO:
        return nexo != null;
    }
    return super.eIsSet(featureID);
  }

} //CompuestaImpl
