/**
 * generated by Xtext 2.10.0-SNAPSHOT
 */
package org.xtext.tesis.gramatica.gramatica.impl;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.xtext.tesis.gramatica.gramatica.Comparacion;
import org.xtext.tesis.gramatica.gramatica.GramaticaPackage;
import org.xtext.tesis.gramatica.gramatica.Obligacion;
import org.xtext.tesis.gramatica.gramatica.Operacion;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Comparacion</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.tesis.gramatica.gramatica.impl.ComparacionImpl#getObligacion <em>Obligacion</em>}</li>
 *   <li>{@link org.xtext.tesis.gramatica.gramatica.impl.ComparacionImpl#getOperacion <em>Operacion</em>}</li>
 * </ul>
 *
 * @generated
 */
public class ComparacionImpl extends MinimalEObjectImpl.Container implements Comparacion
{
  /**
   * The cached value of the '{@link #getObligacion() <em>Obligacion</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getObligacion()
   * @generated
   * @ordered
   */
  protected Obligacion obligacion;

  /**
   * The cached value of the '{@link #getOperacion() <em>Operacion</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getOperacion()
   * @generated
   * @ordered
   */
  protected Operacion operacion;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected ComparacionImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return GramaticaPackage.Literals.COMPARACION;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public Obligacion getObligacion()
  {
    return obligacion;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetObligacion(Obligacion newObligacion, NotificationChain msgs)
  {
    Obligacion oldObligacion = obligacion;
    obligacion = newObligacion;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, GramaticaPackage.COMPARACION__OBLIGACION, oldObligacion, newObligacion);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setObligacion(Obligacion newObligacion)
  {
    if (newObligacion != obligacion)
    {
      NotificationChain msgs = null;
      if (obligacion != null)
        msgs = ((InternalEObject)obligacion).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - GramaticaPackage.COMPARACION__OBLIGACION, null, msgs);
      if (newObligacion != null)
        msgs = ((InternalEObject)newObligacion).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - GramaticaPackage.COMPARACION__OBLIGACION, null, msgs);
      msgs = basicSetObligacion(newObligacion, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, GramaticaPackage.COMPARACION__OBLIGACION, newObligacion, newObligacion));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public Operacion getOperacion()
  {
    return operacion;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetOperacion(Operacion newOperacion, NotificationChain msgs)
  {
    Operacion oldOperacion = operacion;
    operacion = newOperacion;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, GramaticaPackage.COMPARACION__OPERACION, oldOperacion, newOperacion);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setOperacion(Operacion newOperacion)
  {
    if (newOperacion != operacion)
    {
      NotificationChain msgs = null;
      if (operacion != null)
        msgs = ((InternalEObject)operacion).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - GramaticaPackage.COMPARACION__OPERACION, null, msgs);
      if (newOperacion != null)
        msgs = ((InternalEObject)newOperacion).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - GramaticaPackage.COMPARACION__OPERACION, null, msgs);
      msgs = basicSetOperacion(newOperacion, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, GramaticaPackage.COMPARACION__OPERACION, newOperacion, newOperacion));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case GramaticaPackage.COMPARACION__OBLIGACION:
        return basicSetObligacion(null, msgs);
      case GramaticaPackage.COMPARACION__OPERACION:
        return basicSetOperacion(null, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case GramaticaPackage.COMPARACION__OBLIGACION:
        return getObligacion();
      case GramaticaPackage.COMPARACION__OPERACION:
        return getOperacion();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case GramaticaPackage.COMPARACION__OBLIGACION:
        setObligacion((Obligacion)newValue);
        return;
      case GramaticaPackage.COMPARACION__OPERACION:
        setOperacion((Operacion)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case GramaticaPackage.COMPARACION__OBLIGACION:
        setObligacion((Obligacion)null);
        return;
      case GramaticaPackage.COMPARACION__OPERACION:
        setOperacion((Operacion)null);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case GramaticaPackage.COMPARACION__OBLIGACION:
        return obligacion != null;
      case GramaticaPackage.COMPARACION__OPERACION:
        return operacion != null;
    }
    return super.eIsSet(featureID);
  }

} //ComparacionImpl
