/**
 * generated by Xtext 2.10.0-SNAPSHOT
 */
package org.xtext.tesis.gramatica.gramatica.impl;

import org.eclipse.emf.common.notify.Notification;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.xtext.tesis.gramatica.gramatica.GramaticaPackage;
import org.xtext.tesis.gramatica.gramatica.Operacion;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Operacion</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.tesis.gramatica.gramatica.impl.OperacionImpl#getOperacion <em>Operacion</em>}</li>
 * </ul>
 *
 * @generated
 */
public class OperacionImpl extends MinimalEObjectImpl.Container implements Operacion
{
  /**
   * The default value of the '{@link #getOperacion() <em>Operacion</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getOperacion()
   * @generated
   * @ordered
   */
  protected static final String OPERACION_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getOperacion() <em>Operacion</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getOperacion()
   * @generated
   * @ordered
   */
  protected String operacion = OPERACION_EDEFAULT;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected OperacionImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return GramaticaPackage.Literals.OPERACION;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public String getOperacion()
  {
    return operacion;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setOperacion(String newOperacion)
  {
    String oldOperacion = operacion;
    operacion = newOperacion;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, GramaticaPackage.OPERACION__OPERACION, oldOperacion, operacion));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case GramaticaPackage.OPERACION__OPERACION:
        return getOperacion();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case GramaticaPackage.OPERACION__OPERACION:
        setOperacion((String)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case GramaticaPackage.OPERACION__OPERACION:
        setOperacion(OPERACION_EDEFAULT);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case GramaticaPackage.OPERACION__OPERACION:
        return OPERACION_EDEFAULT == null ? operacion != null : !OPERACION_EDEFAULT.equals(operacion);
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuffer result = new StringBuffer(super.toString());
    result.append(" (operacion: ");
    result.append(operacion);
    result.append(')');
    return result.toString();
  }

} //OperacionImpl
