/**
 * generated by Xtext 2.10.0
 */
package org.xtext.tesis.gramatica.gramatica.impl;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.xtext.tesis.gramatica.gramatica.GramaticaPackage;
import org.xtext.tesis.gramatica.gramatica.Oracion;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Oracion</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.tesis.gramatica.gramatica.impl.OracionImpl#getContenido <em>Contenido</em>}</li>
 * </ul>
 *
 * @generated
 */
public class OracionImpl extends MinimalEObjectImpl.Container implements Oracion
{
  /**
   * The cached value of the '{@link #getContenido() <em>Contenido</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getContenido()
   * @generated
   * @ordered
   */
  protected EObject contenido;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected OracionImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return GramaticaPackage.Literals.ORACION;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EObject getContenido()
  {
    return contenido;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetContenido(EObject newContenido, NotificationChain msgs)
  {
    EObject oldContenido = contenido;
    contenido = newContenido;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, GramaticaPackage.ORACION__CONTENIDO, oldContenido, newContenido);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setContenido(EObject newContenido)
  {
    if (newContenido != contenido)
    {
      NotificationChain msgs = null;
      if (contenido != null)
        msgs = ((InternalEObject)contenido).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - GramaticaPackage.ORACION__CONTENIDO, null, msgs);
      if (newContenido != null)
        msgs = ((InternalEObject)newContenido).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - GramaticaPackage.ORACION__CONTENIDO, null, msgs);
      msgs = basicSetContenido(newContenido, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, GramaticaPackage.ORACION__CONTENIDO, newContenido, newContenido));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case GramaticaPackage.ORACION__CONTENIDO:
        return basicSetContenido(null, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case GramaticaPackage.ORACION__CONTENIDO:
        return getContenido();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case GramaticaPackage.ORACION__CONTENIDO:
        setContenido((EObject)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case GramaticaPackage.ORACION__CONTENIDO:
        setContenido((EObject)null);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case GramaticaPackage.ORACION__CONTENIDO:
        return contenido != null;
    }
    return super.eIsSet(featureID);
  }

} //OracionImpl
