/**
 * generated by Xtext 2.10.0
 */
package org.xtext.tesis.gramatica.gramatica.impl;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.xtext.tesis.gramatica.gramatica.GramaticaPackage;
import org.xtext.tesis.gramatica.gramatica.Oracion;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Oracion</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class OracionImpl extends MinimalEObjectImpl.Container implements Oracion
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected OracionImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return GramaticaPackage.Literals.ORACION;
  }

} //OracionImpl
