/**
 * generated by Xtext 2.10.0-SNAPSHOT
 */
package org.xtext.tesis.gramatica.gramatica.impl;

import java.util.Collection;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.eclipse.emf.ecore.util.EObjectContainmentEList;
import org.eclipse.emf.ecore.util.InternalEList;

import org.xtext.tesis.gramatica.gramatica.Atributo;
import org.xtext.tesis.gramatica.gramatica.GramaticaPackage;
import org.xtext.tesis.gramatica.gramatica.Propiedad;
import org.xtext.tesis.gramatica.gramatica.Termino;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Propiedad</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.tesis.gramatica.gramatica.impl.PropiedadImpl#getAtributo <em>Atributo</em>}</li>
 *   <li>{@link org.xtext.tesis.gramatica.gramatica.impl.PropiedadImpl#getTermino <em>Termino</em>}</li>
 * </ul>
 *
 * @generated
 */
public class PropiedadImpl extends MinimalEObjectImpl.Container implements Propiedad
{
  /**
   * The cached value of the '{@link #getAtributo() <em>Atributo</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getAtributo()
   * @generated
   * @ordered
   */
  protected EList<Atributo> atributo;

  /**
   * The cached value of the '{@link #getTermino() <em>Termino</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getTermino()
   * @generated
   * @ordered
   */
  protected Termino termino;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected PropiedadImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return GramaticaPackage.Literals.PROPIEDAD;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EList<Atributo> getAtributo()
  {
    if (atributo == null)
    {
      atributo = new EObjectContainmentEList<Atributo>(Atributo.class, this, GramaticaPackage.PROPIEDAD__ATRIBUTO);
    }
    return atributo;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public Termino getTermino()
  {
    return termino;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetTermino(Termino newTermino, NotificationChain msgs)
  {
    Termino oldTermino = termino;
    termino = newTermino;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, GramaticaPackage.PROPIEDAD__TERMINO, oldTermino, newTermino);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setTermino(Termino newTermino)
  {
    if (newTermino != termino)
    {
      NotificationChain msgs = null;
      if (termino != null)
        msgs = ((InternalEObject)termino).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - GramaticaPackage.PROPIEDAD__TERMINO, null, msgs);
      if (newTermino != null)
        msgs = ((InternalEObject)newTermino).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - GramaticaPackage.PROPIEDAD__TERMINO, null, msgs);
      msgs = basicSetTermino(newTermino, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, GramaticaPackage.PROPIEDAD__TERMINO, newTermino, newTermino));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case GramaticaPackage.PROPIEDAD__ATRIBUTO:
        return ((InternalEList<?>)getAtributo()).basicRemove(otherEnd, msgs);
      case GramaticaPackage.PROPIEDAD__TERMINO:
        return basicSetTermino(null, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case GramaticaPackage.PROPIEDAD__ATRIBUTO:
        return getAtributo();
      case GramaticaPackage.PROPIEDAD__TERMINO:
        return getTermino();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @SuppressWarnings("unchecked")
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case GramaticaPackage.PROPIEDAD__ATRIBUTO:
        getAtributo().clear();
        getAtributo().addAll((Collection<? extends Atributo>)newValue);
        return;
      case GramaticaPackage.PROPIEDAD__TERMINO:
        setTermino((Termino)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case GramaticaPackage.PROPIEDAD__ATRIBUTO:
        getAtributo().clear();
        return;
      case GramaticaPackage.PROPIEDAD__TERMINO:
        setTermino((Termino)null);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case GramaticaPackage.PROPIEDAD__ATRIBUTO:
        return atributo != null && !atributo.isEmpty();
      case GramaticaPackage.PROPIEDAD__TERMINO:
        return termino != null;
    }
    return super.eIsSet(featureID);
  }

} //PropiedadImpl
