/**
 * generated by Xtext 2.10.0
 */
package org.xtext.tesis.gramatica.gramatica.util;

import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.ecore.EPackage;

import org.eclipse.emf.ecore.util.Switch;

import org.xtext.tesis.gramatica.gramatica.*;

/**
 * <!-- begin-user-doc -->
 * The <b>Switch</b> for the model's inheritance hierarchy.
 * It supports the call {@link #doSwitch(EObject) doSwitch(object)}
 * to invoke the <code>caseXXX</code> method for each class of the model,
 * starting with the actual class of the object
 * and proceeding up the inheritance hierarchy
 * until a non-null result is returned,
 * which is the result of the switch.
 * <!-- end-user-doc -->
 * @see org.xtext.tesis.gramatica.gramatica.GramaticaPackage
 * @generated
 */
public class GramaticaSwitch<T> extends Switch<T>
{
  /**
   * The cached model package
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected static GramaticaPackage modelPackage;

  /**
   * Creates an instance of the switch.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public GramaticaSwitch()
  {
    if (modelPackage == null)
    {
      modelPackage = GramaticaPackage.eINSTANCE;
    }
  }

  /**
   * Checks whether this is a switch for the given package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param ePackage the package in question.
   * @return whether this is a switch for the given package.
   * @generated
   */
  @Override
  protected boolean isSwitchFor(EPackage ePackage)
  {
    return ePackage == modelPackage;
  }

  /**
   * Calls <code>caseXXX</code> for each class of the model until one returns a non null result; it yields that result.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the first non-null result returned by a <code>caseXXX</code> call.
   * @generated
   */
  @Override
  protected T doSwitch(int classifierID, EObject theEObject)
  {
    switch (classifierID)
    {
      case GramaticaPackage.DOCUMENTO:
      {
        Documento documento = (Documento)theEObject;
        T result = caseDocumento(documento);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case GramaticaPackage.ORACION:
      {
        Oracion oracion = (Oracion)theEObject;
        T result = caseOracion(oracion);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case GramaticaPackage.SIMPLE:
      {
        Simple simple = (Simple)theEObject;
        T result = caseSimple(simple);
        if (result == null) result = caseOracion(simple);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case GramaticaPackage.DETERMINANTE:
      {
        Determinante determinante = (Determinante)theEObject;
        T result = caseDeterminante(determinante);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case GramaticaPackage.ATRIBUTO:
      {
        Atributo atributo = (Atributo)theEObject;
        T result = caseAtributo(atributo);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case GramaticaPackage.SINTAGMA_PREPOSICIONAL:
      {
        SintagmaPreposicional sintagmaPreposicional = (SintagmaPreposicional)theEObject;
        T result = caseSintagmaPreposicional(sintagmaPreposicional);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case GramaticaPackage.OBLIGACION:
      {
        Obligacion obligacion = (Obligacion)theEObject;
        T result = caseObligacion(obligacion);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case GramaticaPackage.OBLIGACION_DEBER:
      {
        ObligacionDeber obligacionDeber = (ObligacionDeber)theEObject;
        T result = caseObligacionDeber(obligacionDeber);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case GramaticaPackage.NEGACION:
      {
        Negacion negacion = (Negacion)theEObject;
        T result = caseNegacion(negacion);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case GramaticaPackage.OPERACION:
      {
        Operacion operacion = (Operacion)theEObject;
        T result = caseOperacion(operacion);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case GramaticaPackage.CLASE:
      {
        Clase clase = (Clase)theEObject;
        T result = caseClase(clase);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case GramaticaPackage.COMPLEJA:
      {
        Compleja compleja = (Compleja)theEObject;
        T result = caseCompleja(compleja);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      default: return defaultCase(theEObject);
    }
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>Documento</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>Documento</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseDocumento(Documento object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>Oracion</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>Oracion</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseOracion(Oracion object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>Simple</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>Simple</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseSimple(Simple object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>Determinante</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>Determinante</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseDeterminante(Determinante object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>Atributo</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>Atributo</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseAtributo(Atributo object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>Sintagma Preposicional</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>Sintagma Preposicional</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseSintagmaPreposicional(SintagmaPreposicional object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>Obligacion</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>Obligacion</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseObligacion(Obligacion object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>Obligacion Deber</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>Obligacion Deber</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseObligacionDeber(ObligacionDeber object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>Negacion</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>Negacion</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseNegacion(Negacion object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>Operacion</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>Operacion</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseOperacion(Operacion object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>Clase</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>Clase</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseClase(Clase object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>Compleja</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>Compleja</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseCompleja(Compleja object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>EObject</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch, but this is the last case anyway.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>EObject</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject)
   * @generated
   */
  @Override
  public T defaultCase(EObject object)
  {
    return null;
  }

} //GramaticaSwitch
