/*
 * generated by Xtext 2.10.0-SNAPSHOT
 */
package org.xtext.example.lenguajenaturalreducido.ui.contentassist


/**
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#content-assist
 * on how to customize the content assistant.
 */
class LenguajeNaturalReducidoProposalProvider extends AbstractLenguajeNaturalReducidoProposalProvider {
}
