/**
 * generated by Xtext 2.10.0-SNAPSHOT
 */
package org.xtext.tesis.gramatica.gramatica;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Contenido</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.tesis.gramatica.gramatica.Contenido#getSimple <em>Simple</em>}</li>
 *   <li>{@link org.xtext.tesis.gramatica.gramatica.Contenido#getComposicion <em>Composicion</em>}</li>
 * </ul>
 *
 * @see org.xtext.tesis.gramatica.gramatica.GramaticaPackage#getContenido()
 * @model
 * @generated
 */
public interface Contenido extends EObject
{
  /**
   * Returns the value of the '<em><b>Simple</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Simple</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Simple</em>' containment reference.
   * @see #setSimple(EObject)
   * @see org.xtext.tesis.gramatica.gramatica.GramaticaPackage#getContenido_Simple()
   * @model containment="true"
   * @generated
   */
  EObject getSimple();

  /**
   * Sets the value of the '{@link org.xtext.tesis.gramatica.gramatica.Contenido#getSimple <em>Simple</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Simple</em>' containment reference.
   * @see #getSimple()
   * @generated
   */
  void setSimple(EObject value);

  /**
   * Returns the value of the '<em><b>Composicion</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Composicion</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Composicion</em>' containment reference.
   * @see #setComposicion(Composicion)
   * @see org.xtext.tesis.gramatica.gramatica.GramaticaPackage#getContenido_Composicion()
   * @model containment="true"
   * @generated
   */
  Composicion getComposicion();

  /**
   * Sets the value of the '{@link org.xtext.tesis.gramatica.gramatica.Contenido#getComposicion <em>Composicion</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Composicion</em>' containment reference.
   * @see #getComposicion()
   * @generated
   */
  void setComposicion(Composicion value);

} // Contenido
