/**
 * generated by Xtext 2.10.0
 */
package org.xtext.tesis.gramatica.gramatica;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Gramatica</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.tesis.gramatica.gramatica.Gramatica#getOraciones <em>Oraciones</em>}</li>
 * </ul>
 *
 * @see org.xtext.tesis.gramatica.gramatica.GramaticaPackage#getGramatica()
 * @model
 * @generated
 */
public interface Gramatica extends EObject
{
  /**
   * Returns the value of the '<em><b>Oraciones</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.tesis.gramatica.gramatica.Oracion}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Oraciones</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Oraciones</em>' containment reference list.
   * @see org.xtext.tesis.gramatica.gramatica.GramaticaPackage#getGramatica_Oraciones()
   * @model containment="true"
   * @generated
   */
  EList<Oracion> getOraciones();

} // Gramatica
