/**
 * generated by Xtext 2.10.0
 */
package org.xtext.tesis.gramatica.gramatica;

import org.eclipse.emf.ecore.EFactory;

/**
 * <!-- begin-user-doc -->
 * The <b>Factory</b> for the model.
 * It provides a create method for each non-abstract class of the model.
 * <!-- end-user-doc -->
 * @see org.xtext.tesis.gramatica.gramatica.GramaticaPackage
 * @generated
 */
public interface GramaticaFactory extends EFactory
{
  /**
   * The singleton instance of the factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  GramaticaFactory eINSTANCE = org.xtext.tesis.gramatica.gramatica.impl.GramaticaFactoryImpl.init();

  /**
   * Returns a new object of class '<em>Gramatica</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Gramatica</em>'.
   * @generated
   */
  Gramatica createGramatica();

  /**
   * Returns a new object of class '<em>Oracion</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Oracion</em>'.
   * @generated
   */
  Oracion createOracion();

  /**
   * Returns a new object of class '<em>Simple</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Simple</em>'.
   * @generated
   */
  Simple createSimple();

  /**
   * Returns a new object of class '<em>Compleja</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Compleja</em>'.
   * @generated
   */
  Compleja createCompleja();

  /**
   * Returns a new object of class '<em>Atributo</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Atributo</em>'.
   * @generated
   */
  Atributo createAtributo();

  /**
   * Returns a new object of class '<em>Clase</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Clase</em>'.
   * @generated
   */
  Clase createClase();

  /**
   * Returns the package supported by this factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the package supported by this factory.
   * @generated
   */
  GramaticaPackage getGramaticaPackage();

} //GramaticaFactory
