/**
 * generated by Xtext 2.10.0-SNAPSHOT
 */
package org.xtext.tesis.gramatica.gramatica;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Obligacion</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.tesis.gramatica.gramatica.Obligacion#getNegacion <em>Negacion</em>}</li>
 *   <li>{@link org.xtext.tesis.gramatica.gramatica.Obligacion#getObligacionDeber <em>Obligacion Deber</em>}</li>
 * </ul>
 *
 * @see org.xtext.tesis.gramatica.gramatica.GramaticaPackage#getObligacion()
 * @model
 * @generated
 */
public interface Obligacion extends EObject
{
  /**
   * Returns the value of the '<em><b>Negacion</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Negacion</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Negacion</em>' attribute.
   * @see #setNegacion(String)
   * @see org.xtext.tesis.gramatica.gramatica.GramaticaPackage#getObligacion_Negacion()
   * @model
   * @generated
   */
  String getNegacion();

  /**
   * Sets the value of the '{@link org.xtext.tesis.gramatica.gramatica.Obligacion#getNegacion <em>Negacion</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Negacion</em>' attribute.
   * @see #getNegacion()
   * @generated
   */
  void setNegacion(String value);

  /**
   * Returns the value of the '<em><b>Obligacion Deber</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Obligacion Deber</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Obligacion Deber</em>' attribute.
   * @see #setObligacionDeber(String)
   * @see org.xtext.tesis.gramatica.gramatica.GramaticaPackage#getObligacion_ObligacionDeber()
   * @model
   * @generated
   */
  String getObligacionDeber();

  /**
   * Sets the value of the '{@link org.xtext.tesis.gramatica.gramatica.Obligacion#getObligacionDeber <em>Obligacion Deber</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Obligacion Deber</em>' attribute.
   * @see #getObligacionDeber()
   * @generated
   */
  void setObligacionDeber(String value);

} // Obligacion
