/**
 * generated by Xtext 2.10.0-SNAPSHOT
 */
package org.xtext.tesis.gramatica.gramatica;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Termino</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.tesis.gramatica.gramatica.Termino#getIndeterminante <em>Indeterminante</em>}</li>
 *   <li>{@link org.xtext.tesis.gramatica.gramatica.Termino#getContexto <em>Contexto</em>}</li>
 * </ul>
 *
 * @see org.xtext.tesis.gramatica.gramatica.GramaticaPackage#getTermino()
 * @model
 * @generated
 */
public interface Termino extends EObject
{
  /**
   * Returns the value of the '<em><b>Indeterminante</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Indeterminante</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Indeterminante</em>' containment reference.
   * @see #setIndeterminante(Indeterminante)
   * @see org.xtext.tesis.gramatica.gramatica.GramaticaPackage#getTermino_Indeterminante()
   * @model containment="true"
   * @generated
   */
  Indeterminante getIndeterminante();

  /**
   * Sets the value of the '{@link org.xtext.tesis.gramatica.gramatica.Termino#getIndeterminante <em>Indeterminante</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Indeterminante</em>' containment reference.
   * @see #getIndeterminante()
   * @generated
   */
  void setIndeterminante(Indeterminante value);

  /**
   * Returns the value of the '<em><b>Contexto</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Contexto</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Contexto</em>' containment reference.
   * @see #setContexto(Contexto)
   * @see org.xtext.tesis.gramatica.gramatica.GramaticaPackage#getTermino_Contexto()
   * @model containment="true"
   * @generated
   */
  Contexto getContexto();

  /**
   * Sets the value of the '{@link org.xtext.tesis.gramatica.gramatica.Termino#getContexto <em>Contexto</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Contexto</em>' containment reference.
   * @see #getContexto()
   * @generated
   */
  void setContexto(Contexto value);

} // Termino
