/**
 * generated by Xtext 2.10.0-SNAPSHOT
 */
package org.xtext.tesina.lenguajeNaturalReducido;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Atributo</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.tesina.lenguajeNaturalReducido.Atributo#getDeterminante <em>Determinante</em>}</li>
 *   <li>{@link org.xtext.tesina.lenguajeNaturalReducido.Atributo#getPrefijo <em>Prefijo</em>}</li>
 *   <li>{@link org.xtext.tesina.lenguajeNaturalReducido.Atributo#getNombre <em>Nombre</em>}</li>
 *   <li>{@link org.xtext.tesina.lenguajeNaturalReducido.Atributo#getEnlace <em>Enlace</em>}</li>
 * </ul>
 *
 * @see org.xtext.tesina.lenguajeNaturalReducido.LenguajeNaturalReducidoPackage#getAtributo()
 * @model
 * @generated
 */
public interface Atributo extends EObject
{
  /**
   * Returns the value of the '<em><b>Determinante</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Determinante</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Determinante</em>' attribute.
   * @see #setDeterminante(String)
   * @see org.xtext.tesina.lenguajeNaturalReducido.LenguajeNaturalReducidoPackage#getAtributo_Determinante()
   * @model
   * @generated
   */
  String getDeterminante();

  /**
   * Sets the value of the '{@link org.xtext.tesina.lenguajeNaturalReducido.Atributo#getDeterminante <em>Determinante</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Determinante</em>' attribute.
   * @see #getDeterminante()
   * @generated
   */
  void setDeterminante(String value);

  /**
   * Returns the value of the '<em><b>Prefijo</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Prefijo</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Prefijo</em>' attribute.
   * @see #setPrefijo(String)
   * @see org.xtext.tesina.lenguajeNaturalReducido.LenguajeNaturalReducidoPackage#getAtributo_Prefijo()
   * @model
   * @generated
   */
  String getPrefijo();

  /**
   * Sets the value of the '{@link org.xtext.tesina.lenguajeNaturalReducido.Atributo#getPrefijo <em>Prefijo</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Prefijo</em>' attribute.
   * @see #getPrefijo()
   * @generated
   */
  void setPrefijo(String value);

  /**
   * Returns the value of the '<em><b>Nombre</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Nombre</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Nombre</em>' attribute.
   * @see #setNombre(String)
   * @see org.xtext.tesina.lenguajeNaturalReducido.LenguajeNaturalReducidoPackage#getAtributo_Nombre()
   * @model
   * @generated
   */
  String getNombre();

  /**
   * Sets the value of the '{@link org.xtext.tesina.lenguajeNaturalReducido.Atributo#getNombre <em>Nombre</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Nombre</em>' attribute.
   * @see #getNombre()
   * @generated
   */
  void setNombre(String value);

  /**
   * Returns the value of the '<em><b>Enlace</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Enlace</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Enlace</em>' attribute.
   * @see #setEnlace(String)
   * @see org.xtext.tesina.lenguajeNaturalReducido.LenguajeNaturalReducidoPackage#getAtributo_Enlace()
   * @model
   * @generated
   */
  String getEnlace();

  /**
   * Sets the value of the '{@link org.xtext.tesina.lenguajeNaturalReducido.Atributo#getEnlace <em>Enlace</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Enlace</em>' attribute.
   * @see #getEnlace()
   * @generated
   */
  void setEnlace(String value);

} // Atributo
