/**
 * generated by Xtext 2.10.0-SNAPSHOT
 */
package org.xtext.tesina.lenguajeNaturalReducido;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Documento</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.tesina.lenguajeNaturalReducido.Documento#getEncabezado <em>Encabezado</em>}</li>
 *   <li>{@link org.xtext.tesina.lenguajeNaturalReducido.Documento#getOraciones <em>Oraciones</em>}</li>
 * </ul>
 *
 * @see org.xtext.tesina.lenguajeNaturalReducido.LenguajeNaturalReducidoPackage#getDocumento()
 * @model
 * @generated
 */
public interface Documento extends EObject
{
  /**
   * Returns the value of the '<em><b>Encabezado</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Encabezado</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Encabezado</em>' containment reference.
   * @see #setEncabezado(Literal)
   * @see org.xtext.tesina.lenguajeNaturalReducido.LenguajeNaturalReducidoPackage#getDocumento_Encabezado()
   * @model containment="true"
   * @generated
   */
  Literal getEncabezado();

  /**
   * Sets the value of the '{@link org.xtext.tesina.lenguajeNaturalReducido.Documento#getEncabezado <em>Encabezado</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Encabezado</em>' containment reference.
   * @see #getEncabezado()
   * @generated
   */
  void setEncabezado(Literal value);

  /**
   * Returns the value of the '<em><b>Oraciones</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.tesina.lenguajeNaturalReducido.Oracion}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Oraciones</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Oraciones</em>' containment reference list.
   * @see org.xtext.tesina.lenguajeNaturalReducido.LenguajeNaturalReducidoPackage#getDocumento_Oraciones()
   * @model containment="true"
   * @generated
   */
  EList<Oracion> getOraciones();

} // Documento
