/**
 * generated by Xtext 2.10.0-SNAPSHOT
 */
package org.xtext.tesina.lenguajeNaturalReducido;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Expresion Derecha</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.tesina.lenguajeNaturalReducido.ExpresionDerecha#getComparacion <em>Comparacion</em>}</li>
 *   <li>{@link org.xtext.tesina.lenguajeNaturalReducido.ExpresionDerecha#getExpresion <em>Expresion</em>}</li>
 * </ul>
 *
 * @see org.xtext.tesina.lenguajeNaturalReducido.LenguajeNaturalReducidoPackage#getExpresionDerecha()
 * @model
 * @generated
 */
public interface ExpresionDerecha extends EObject
{
  /**
   * Returns the value of the '<em><b>Comparacion</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Comparacion</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Comparacion</em>' containment reference.
   * @see #setComparacion(Comparacion)
   * @see org.xtext.tesina.lenguajeNaturalReducido.LenguajeNaturalReducidoPackage#getExpresionDerecha_Comparacion()
   * @model containment="true"
   * @generated
   */
  Comparacion getComparacion();

  /**
   * Sets the value of the '{@link org.xtext.tesina.lenguajeNaturalReducido.ExpresionDerecha#getComparacion <em>Comparacion</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Comparacion</em>' containment reference.
   * @see #getComparacion()
   * @generated
   */
  void setComparacion(Comparacion value);

  /**
   * Returns the value of the '<em><b>Expresion</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Expresion</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Expresion</em>' containment reference.
   * @see #setExpresion(Expresion)
   * @see org.xtext.tesina.lenguajeNaturalReducido.LenguajeNaturalReducidoPackage#getExpresionDerecha_Expresion()
   * @model containment="true"
   * @generated
   */
  Expresion getExpresion();

  /**
   * Sets the value of the '{@link org.xtext.tesina.lenguajeNaturalReducido.ExpresionDerecha#getExpresion <em>Expresion</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Expresion</em>' containment reference.
   * @see #getExpresion()
   * @generated
   */
  void setExpresion(Expresion value);

} // ExpresionDerecha
