/**
 * generated by Xtext 2.10.0-SNAPSHOT
 */
package org.xtext.tesina.lenguajeNaturalReducido;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Nexo</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.tesina.lenguajeNaturalReducido.Nexo#getNexo <em>Nexo</em>}</li>
 * </ul>
 *
 * @see org.xtext.tesina.lenguajeNaturalReducido.LenguajeNaturalReducidoPackage#getNexo()
 * @model
 * @generated
 */
public interface Nexo extends EObject
{
  /**
   * Returns the value of the '<em><b>Nexo</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Nexo</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Nexo</em>' attribute.
   * @see #setNexo(String)
   * @see org.xtext.tesina.lenguajeNaturalReducido.LenguajeNaturalReducidoPackage#getNexo_Nexo()
   * @model
   * @generated
   */
  String getNexo();

  /**
   * Sets the value of the '{@link org.xtext.tesina.lenguajeNaturalReducido.Nexo#getNexo <em>Nexo</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Nexo</em>' attribute.
   * @see #getNexo()
   * @generated
   */
  void setNexo(String value);

} // Nexo
