/**
 * generated by Xtext 2.10.0-SNAPSHOT
 */
package org.xtext.tesina.lenguajeNaturalReducido;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Oracion</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.tesina.lenguajeNaturalReducido.Oracion#getContenido <em>Contenido</em>}</li>
 * </ul>
 *
 * @see org.xtext.tesina.lenguajeNaturalReducido.LenguajeNaturalReducidoPackage#getOracion()
 * @model
 * @generated
 */
public interface Oracion extends EObject
{
  /**
   * Returns the value of the '<em><b>Contenido</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Contenido</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Contenido</em>' containment reference.
   * @see #setContenido(Contenido)
   * @see org.xtext.tesina.lenguajeNaturalReducido.LenguajeNaturalReducidoPackage#getOracion_Contenido()
   * @model containment="true"
   * @generated
   */
  Contenido getContenido();

  /**
   * Sets the value of the '{@link org.xtext.tesina.lenguajeNaturalReducido.Oracion#getContenido <em>Contenido</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Contenido</em>' containment reference.
   * @see #getContenido()
   * @generated
   */
  void setContenido(Contenido value);

} // Oracion
