/**
 * generated by Xtext 2.10.0-SNAPSHOT
 */
package org.xtext.tesina.lenguajeNaturalReducido;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Propiedad</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.tesina.lenguajeNaturalReducido.Propiedad#getAtributo <em>Atributo</em>}</li>
 *   <li>{@link org.xtext.tesina.lenguajeNaturalReducido.Propiedad#getTermino <em>Termino</em>}</li>
 *   <li>{@link org.xtext.tesina.lenguajeNaturalReducido.Propiedad#getIteracion <em>Iteracion</em>}</li>
 * </ul>
 *
 * @see org.xtext.tesina.lenguajeNaturalReducido.LenguajeNaturalReducidoPackage#getPropiedad()
 * @model
 * @generated
 */
public interface Propiedad extends EObject
{
  /**
   * Returns the value of the '<em><b>Atributo</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.tesina.lenguajeNaturalReducido.Atributo}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Atributo</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Atributo</em>' containment reference list.
   * @see org.xtext.tesina.lenguajeNaturalReducido.LenguajeNaturalReducidoPackage#getPropiedad_Atributo()
   * @model containment="true"
   * @generated
   */
  EList<Atributo> getAtributo();

  /**
   * Returns the value of the '<em><b>Termino</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Termino</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Termino</em>' containment reference.
   * @see #setTermino(Termino)
   * @see org.xtext.tesina.lenguajeNaturalReducido.LenguajeNaturalReducidoPackage#getPropiedad_Termino()
   * @model containment="true"
   * @generated
   */
  Termino getTermino();

  /**
   * Sets the value of the '{@link org.xtext.tesina.lenguajeNaturalReducido.Propiedad#getTermino <em>Termino</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Termino</em>' containment reference.
   * @see #getTermino()
   * @generated
   */
  void setTermino(Termino value);

  /**
   * Returns the value of the '<em><b>Iteracion</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.tesina.lenguajeNaturalReducido.Iteracion}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Iteracion</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Iteracion</em>' containment reference list.
   * @see org.xtext.tesina.lenguajeNaturalReducido.LenguajeNaturalReducidoPackage#getPropiedad_Iteracion()
   * @model containment="true"
   * @generated
   */
  EList<Iteracion> getIteracion();

} // Propiedad
