/**
 * generated by Xtext 2.10.0-SNAPSHOT
 */
package org.xtext.tesina.lenguajeNaturalReducido.util;

import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.ecore.EPackage;

import org.eclipse.emf.ecore.util.Switch;

import org.xtext.tesina.lenguajeNaturalReducido.*;

/**
 * <!-- begin-user-doc -->
 * The <b>Switch</b> for the model's inheritance hierarchy.
 * It supports the call {@link #doSwitch(EObject) doSwitch(object)}
 * to invoke the <code>caseXXX</code> method for each class of the model,
 * starting with the actual class of the object
 * and proceeding up the inheritance hierarchy
 * until a non-null result is returned,
 * which is the result of the switch.
 * <!-- end-user-doc -->
 * @see org.xtext.tesina.lenguajeNaturalReducido.LenguajeNaturalReducidoPackage
 * @generated
 */
public class LenguajeNaturalReducidoSwitch<T> extends Switch<T>
{
  /**
   * The cached model package
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected static LenguajeNaturalReducidoPackage modelPackage;

  /**
   * Creates an instance of the switch.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public LenguajeNaturalReducidoSwitch()
  {
    if (modelPackage == null)
    {
      modelPackage = LenguajeNaturalReducidoPackage.eINSTANCE;
    }
  }

  /**
   * Checks whether this is a switch for the given package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param ePackage the package in question.
   * @return whether this is a switch for the given package.
   * @generated
   */
  @Override
  protected boolean isSwitchFor(EPackage ePackage)
  {
    return ePackage == modelPackage;
  }

  /**
   * Calls <code>caseXXX</code> for each class of the model until one returns a non null result; it yields that result.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the first non-null result returned by a <code>caseXXX</code> call.
   * @generated
   */
  @Override
  protected T doSwitch(int classifierID, EObject theEObject)
  {
    switch (classifierID)
    {
      case LenguajeNaturalReducidoPackage.DOCUMENTO:
      {
        Documento documento = (Documento)theEObject;
        T result = caseDocumento(documento);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case LenguajeNaturalReducidoPackage.ORACION:
      {
        Oracion oracion = (Oracion)theEObject;
        T result = caseOracion(oracion);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case LenguajeNaturalReducidoPackage.CONTENIDO:
      {
        Contenido contenido = (Contenido)theEObject;
        T result = caseContenido(contenido);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case LenguajeNaturalReducidoPackage.SIMPLE:
      {
        Simple simple = (Simple)theEObject;
        T result = caseSimple(simple);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case LenguajeNaturalReducidoPackage.EXPRESION_DERECHA:
      {
        ExpresionDerecha expresionDerecha = (ExpresionDerecha)theEObject;
        T result = caseExpresionDerecha(expresionDerecha);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case LenguajeNaturalReducidoPackage.COMPOSICION:
      {
        Composicion composicion = (Composicion)theEObject;
        T result = caseComposicion(composicion);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case LenguajeNaturalReducidoPackage.NEXO:
      {
        Nexo nexo = (Nexo)theEObject;
        T result = caseNexo(nexo);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case LenguajeNaturalReducidoPackage.EXPRESION:
      {
        Expresion expresion = (Expresion)theEObject;
        T result = caseExpresion(expresion);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case LenguajeNaturalReducidoPackage.COMPARACION:
      {
        Comparacion comparacion = (Comparacion)theEObject;
        T result = caseComparacion(comparacion);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case LenguajeNaturalReducidoPackage.PROPIEDAD:
      {
        Propiedad propiedad = (Propiedad)theEObject;
        T result = casePropiedad(propiedad);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case LenguajeNaturalReducidoPackage.ITERACION:
      {
        Iteracion iteracion = (Iteracion)theEObject;
        T result = caseIteracion(iteracion);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case LenguajeNaturalReducidoPackage.ATRIBUTO:
      {
        Atributo atributo = (Atributo)theEObject;
        T result = caseAtributo(atributo);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case LenguajeNaturalReducidoPackage.TERMINO:
      {
        Termino termino = (Termino)theEObject;
        T result = caseTermino(termino);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case LenguajeNaturalReducidoPackage.AFIRMACION:
      {
        Afirmacion afirmacion = (Afirmacion)theEObject;
        T result = caseAfirmacion(afirmacion);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case LenguajeNaturalReducidoPackage.OPERACION:
      {
        Operacion operacion = (Operacion)theEObject;
        T result = caseOperacion(operacion);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case LenguajeNaturalReducidoPackage.LITERAL:
      {
        Literal literal = (Literal)theEObject;
        T result = caseLiteral(literal);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      default: return defaultCase(theEObject);
    }
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>Documento</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>Documento</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseDocumento(Documento object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>Oracion</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>Oracion</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseOracion(Oracion object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>Contenido</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>Contenido</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseContenido(Contenido object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>Simple</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>Simple</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseSimple(Simple object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>Expresion Derecha</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>Expresion Derecha</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseExpresionDerecha(ExpresionDerecha object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>Composicion</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>Composicion</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseComposicion(Composicion object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>Nexo</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>Nexo</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseNexo(Nexo object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>Expresion</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>Expresion</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseExpresion(Expresion object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>Comparacion</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>Comparacion</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseComparacion(Comparacion object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>Propiedad</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>Propiedad</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T casePropiedad(Propiedad object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>Iteracion</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>Iteracion</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseIteracion(Iteracion object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>Atributo</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>Atributo</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseAtributo(Atributo object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>Termino</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>Termino</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseTermino(Termino object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>Afirmacion</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>Afirmacion</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseAfirmacion(Afirmacion object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>Operacion</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>Operacion</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseOperacion(Operacion object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>Literal</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>Literal</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseLiteral(Literal object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>EObject</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch, but this is the last case anyway.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>EObject</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject)
   * @generated
   */
  @Override
  public T defaultCase(EObject object)
  {
    return null;
  }

} //LenguajeNaturalReducidoSwitch
