/*
 * generated by Xtext 2.10.0-SNAPSHOT
 */
package org.xtext.tesis.gramatica.serializer;

import com.google.inject.Inject;
import java.util.Set;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.xtext.Action;
import org.eclipse.xtext.Parameter;
import org.eclipse.xtext.ParserRule;
import org.eclipse.xtext.serializer.ISerializationContext;
import org.eclipse.xtext.serializer.acceptor.SequenceFeeder;
import org.eclipse.xtext.serializer.sequencer.AbstractDelegatingSemanticSequencer;
import org.eclipse.xtext.serializer.sequencer.ITransientValueService.ValueTransient;
import org.xtext.tesis.gramatica.gramatica.Atributo;
import org.xtext.tesis.gramatica.gramatica.Compuesta;
import org.xtext.tesis.gramatica.gramatica.Contexto;
import org.xtext.tesis.gramatica.gramatica.Determinante;
import org.xtext.tesis.gramatica.gramatica.Documento;
import org.xtext.tesis.gramatica.gramatica.Enlace;
import org.xtext.tesis.gramatica.gramatica.GramaticaPackage;
import org.xtext.tesis.gramatica.gramatica.Indeterminante;
import org.xtext.tesis.gramatica.gramatica.Literal;
import org.xtext.tesis.gramatica.gramatica.Nexo;
import org.xtext.tesis.gramatica.gramatica.Obligacion;
import org.xtext.tesis.gramatica.gramatica.Operacion;
import org.xtext.tesis.gramatica.gramatica.Oracion;
import org.xtext.tesis.gramatica.gramatica.Simple;
import org.xtext.tesis.gramatica.gramatica.SintagmaPreposicional;
import org.xtext.tesis.gramatica.gramatica.Termino;
import org.xtext.tesis.gramatica.services.GramaticaGrammarAccess;

@SuppressWarnings("all")
public class GramaticaSemanticSequencer extends AbstractDelegatingSemanticSequencer {

	@Inject
	private GramaticaGrammarAccess grammarAccess;
	
	@Override
	public void sequence(ISerializationContext context, EObject semanticObject) {
		EPackage epackage = semanticObject.eClass().getEPackage();
		ParserRule rule = context.getParserRule();
		Action action = context.getAssignedAction();
		Set<Parameter> parameters = context.getEnabledBooleanParameters();
		if (epackage == GramaticaPackage.eINSTANCE)
			switch (semanticObject.eClass().getClassifierID()) {
			case GramaticaPackage.ATRIBUTO:
				sequence_Atributo(context, (Atributo) semanticObject); 
				return; 
			case GramaticaPackage.COMPUESTA:
				sequence_Compuesta(context, (Compuesta) semanticObject); 
				return; 
			case GramaticaPackage.CONTEXTO:
				sequence_Contexto(context, (Contexto) semanticObject); 
				return; 
			case GramaticaPackage.DETERMINANTE:
				sequence_Determinante(context, (Determinante) semanticObject); 
				return; 
			case GramaticaPackage.DOCUMENTO:
				sequence_Documento(context, (Documento) semanticObject); 
				return; 
			case GramaticaPackage.ENLACE:
				sequence_Enlace(context, (Enlace) semanticObject); 
				return; 
			case GramaticaPackage.INDETERMINANTE:
				sequence_Indeterminante(context, (Indeterminante) semanticObject); 
				return; 
			case GramaticaPackage.LITERAL:
				sequence_Literal(context, (Literal) semanticObject); 
				return; 
			case GramaticaPackage.NEXO:
				sequence_Nexo(context, (Nexo) semanticObject); 
				return; 
			case GramaticaPackage.OBLIGACION:
				sequence_Obligacion(context, (Obligacion) semanticObject); 
				return; 
			case GramaticaPackage.OPERACION:
				sequence_Operacion(context, (Operacion) semanticObject); 
				return; 
			case GramaticaPackage.ORACION:
				sequence_Oracion(context, (Oracion) semanticObject); 
				return; 
			case GramaticaPackage.SIMPLE:
				sequence_Simple(context, (Simple) semanticObject); 
				return; 
			case GramaticaPackage.SINTAGMA_PREPOSICIONAL:
				sequence_SintagmaPreposicional(context, (SintagmaPreposicional) semanticObject); 
				return; 
			case GramaticaPackage.TERMINO:
				sequence_Termino(context, (Termino) semanticObject); 
				return; 
			}
		if (errorAcceptor != null)
			errorAcceptor.accept(diagnosticProvider.createInvalidContextOrTypeDiagnostic(semanticObject, context));
	}
	
	/**
	 * Contexts:
	 *     Atributo returns Atributo
	 *
	 * Constraint:
	 *     nombre=ID
	 */
	protected void sequence_Atributo(ISerializationContext context, Atributo semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, GramaticaPackage.Literals.ATRIBUTO__NOMBRE) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, GramaticaPackage.Literals.ATRIBUTO__NOMBRE));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getAtributoAccess().getNombreIDTerminalRuleCall_0(), semanticObject.getNombre());
		feeder.finish();
	}
	
	
	/**
	 * Contexts:
	 *     Compuesta returns Compuesta
	 *
	 * Constraint:
	 *     (simple=Simple nexo=Nexo oracion=Oracion extraStr=STRING)
	 */
	protected void sequence_Compuesta(ISerializationContext context, Compuesta semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, GramaticaPackage.Literals.COMPUESTA__SIMPLE) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, GramaticaPackage.Literals.COMPUESTA__SIMPLE));
			if (transientValues.isValueTransient(semanticObject, GramaticaPackage.Literals.COMPUESTA__NEXO) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, GramaticaPackage.Literals.COMPUESTA__NEXO));
			if (transientValues.isValueTransient(semanticObject, GramaticaPackage.Literals.COMPUESTA__ORACION) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, GramaticaPackage.Literals.COMPUESTA__ORACION));
			if (transientValues.isValueTransient(semanticObject, GramaticaPackage.Literals.COMPUESTA__EXTRA_STR) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, GramaticaPackage.Literals.COMPUESTA__EXTRA_STR));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getCompuestaAccess().getSimpleSimpleParserRuleCall_0_0(), semanticObject.getSimple());
		feeder.accept(grammarAccess.getCompuestaAccess().getNexoNexoParserRuleCall_1_0(), semanticObject.getNexo());
		feeder.accept(grammarAccess.getCompuestaAccess().getOracionOracionParserRuleCall_2_0(), semanticObject.getOracion());
		feeder.accept(grammarAccess.getCompuestaAccess().getExtraStrSTRINGTerminalRuleCall_3_0(), semanticObject.getExtraStr());
		feeder.finish();
	}
	
	
	/**
	 * Contexts:
	 *     Contexto returns Contexto
	 *
	 * Constraint:
	 *     nombre=ID
	 */
	protected void sequence_Contexto(ISerializationContext context, Contexto semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, GramaticaPackage.Literals.CONTEXTO__NOMBRE) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, GramaticaPackage.Literals.CONTEXTO__NOMBRE));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getContextoAccess().getNombreIDTerminalRuleCall_0(), semanticObject.getNombre());
		feeder.finish();
	}
	
	
	/**
	 * Contexts:
	 *     Determinante returns Determinante
	 *
	 * Constraint:
	 *     valor='El/La'
	 */
	protected void sequence_Determinante(ISerializationContext context, Determinante semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, GramaticaPackage.Literals.DETERMINANTE__VALOR) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, GramaticaPackage.Literals.DETERMINANTE__VALOR));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getDeterminanteAccess().getValorElLaKeyword_0(), semanticObject.getValor());
		feeder.finish();
	}
	
	
	/**
	 * Contexts:
	 *     Documento returns Documento
	 *
	 * Constraint:
	 *     (pathModelo=STRING pathOcl=STRING oraciones+=Oracion*)
	 */
	protected void sequence_Documento(ISerializationContext context, Documento semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Contexts:
	 *     Enlace returns Enlace
	 *
	 * Constraint:
	 *     valor='de'
	 */
	protected void sequence_Enlace(ISerializationContext context, Enlace semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, GramaticaPackage.Literals.ENLACE__VALOR) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, GramaticaPackage.Literals.ENLACE__VALOR));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getEnlaceAccess().getValorDeKeyword_0(), semanticObject.getValor());
		feeder.finish();
	}
	
	
	/**
	 * Contexts:
	 *     Indeterminante returns Indeterminante
	 *
	 * Constraint:
	 *     valor='un/una'
	 */
	protected void sequence_Indeterminante(ISerializationContext context, Indeterminante semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, GramaticaPackage.Literals.INDETERMINANTE__VALOR) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, GramaticaPackage.Literals.INDETERMINANTE__VALOR));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getIndeterminanteAccess().getValorUnUnaKeyword_0(), semanticObject.getValor());
		feeder.finish();
	}
	
	
	/**
	 * Contexts:
	 *     Literal returns Literal
	 *
	 * Constraint:
	 *     valor=STRING
	 */
	protected void sequence_Literal(ISerializationContext context, Literal semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, GramaticaPackage.Literals.LITERAL__VALOR) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, GramaticaPackage.Literals.LITERAL__VALOR));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getLiteralAccess().getValorSTRINGTerminalRuleCall_0(), semanticObject.getValor());
		feeder.finish();
	}
	
	
	/**
	 * Contexts:
	 *     Nexo returns Nexo
	 *
	 * Constraint:
	 *     (valor='y' | valor='o')
	 */
	protected void sequence_Nexo(ISerializationContext context, Nexo semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Contexts:
	 *     Obligacion returns Obligacion
	 *
	 * Constraint:
	 *     (negacion='no'? obligacionDeber='debe ser')
	 */
	protected void sequence_Obligacion(ISerializationContext context, Obligacion semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Contexts:
	 *     Operacion returns Operacion
	 *
	 * Constraint:
	 *     (
	 *         descripcion='mayor que' | 
	 *         descripcion='menor que' | 
	 *         descripcion='igual a' | 
	 *         descripcion='mayor o igual a' | 
	 *         descripcion='menor o igual a' | 
	 *         descripcion='distinto de' | 
	 *         descripcion='al menos'
	 *     )
	 */
	protected void sequence_Operacion(ISerializationContext context, Operacion semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Contexts:
	 *     Oracion returns Oracion
	 *
	 * Constraint:
	 *     (contenido=Compuesta | contenido=Simple)
	 */
	protected void sequence_Oracion(ISerializationContext context, Oracion semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Contexts:
	 *     Simple returns Simple
	 *
	 * Constraint:
	 *     (
	 *         determinante=Determinante 
	 *         atributo=Atributo 
	 *         sintagma=SintagmaPreposicional 
	 *         obligacion=Obligacion 
	 *         operacion=Operacion 
	 *         literal=Literal
	 *     )
	 */
	protected void sequence_Simple(ISerializationContext context, Simple semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, GramaticaPackage.Literals.SIMPLE__DETERMINANTE) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, GramaticaPackage.Literals.SIMPLE__DETERMINANTE));
			if (transientValues.isValueTransient(semanticObject, GramaticaPackage.Literals.SIMPLE__ATRIBUTO) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, GramaticaPackage.Literals.SIMPLE__ATRIBUTO));
			if (transientValues.isValueTransient(semanticObject, GramaticaPackage.Literals.SIMPLE__SINTAGMA) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, GramaticaPackage.Literals.SIMPLE__SINTAGMA));
			if (transientValues.isValueTransient(semanticObject, GramaticaPackage.Literals.SIMPLE__OBLIGACION) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, GramaticaPackage.Literals.SIMPLE__OBLIGACION));
			if (transientValues.isValueTransient(semanticObject, GramaticaPackage.Literals.SIMPLE__OPERACION) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, GramaticaPackage.Literals.SIMPLE__OPERACION));
			if (transientValues.isValueTransient(semanticObject, GramaticaPackage.Literals.SIMPLE__LITERAL) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, GramaticaPackage.Literals.SIMPLE__LITERAL));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getSimpleAccess().getDeterminanteDeterminanteParserRuleCall_0_0(), semanticObject.getDeterminante());
		feeder.accept(grammarAccess.getSimpleAccess().getAtributoAtributoParserRuleCall_1_0(), semanticObject.getAtributo());
		feeder.accept(grammarAccess.getSimpleAccess().getSintagmaSintagmaPreposicionalParserRuleCall_2_0(), semanticObject.getSintagma());
		feeder.accept(grammarAccess.getSimpleAccess().getObligacionObligacionParserRuleCall_3_0(), semanticObject.getObligacion());
		feeder.accept(grammarAccess.getSimpleAccess().getOperacionOperacionParserRuleCall_4_0(), semanticObject.getOperacion());
		feeder.accept(grammarAccess.getSimpleAccess().getLiteralLiteralParserRuleCall_5_0(), semanticObject.getLiteral());
		feeder.finish();
	}
	
	
	/**
	 * Contexts:
	 *     SintagmaPreposicional returns SintagmaPreposicional
	 *
	 * Constraint:
	 *     (enlace=Enlace termino=Termino)
	 */
	protected void sequence_SintagmaPreposicional(ISerializationContext context, SintagmaPreposicional semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, GramaticaPackage.Literals.SINTAGMA_PREPOSICIONAL__ENLACE) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, GramaticaPackage.Literals.SINTAGMA_PREPOSICIONAL__ENLACE));
			if (transientValues.isValueTransient(semanticObject, GramaticaPackage.Literals.SINTAGMA_PREPOSICIONAL__TERMINO) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, GramaticaPackage.Literals.SINTAGMA_PREPOSICIONAL__TERMINO));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getSintagmaPreposicionalAccess().getEnlaceEnlaceParserRuleCall_0_0(), semanticObject.getEnlace());
		feeder.accept(grammarAccess.getSintagmaPreposicionalAccess().getTerminoTerminoParserRuleCall_1_0(), semanticObject.getTermino());
		feeder.finish();
	}
	
	
	/**
	 * Contexts:
	 *     Termino returns Termino
	 *
	 * Constraint:
	 *     (indeterminante=Indeterminante contexto=Contexto)
	 */
	protected void sequence_Termino(ISerializationContext context, Termino semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, GramaticaPackage.Literals.TERMINO__INDETERMINANTE) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, GramaticaPackage.Literals.TERMINO__INDETERMINANTE));
			if (transientValues.isValueTransient(semanticObject, GramaticaPackage.Literals.TERMINO__CONTEXTO) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, GramaticaPackage.Literals.TERMINO__CONTEXTO));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getTerminoAccess().getIndeterminanteIndeterminanteParserRuleCall_0_0(), semanticObject.getIndeterminante());
		feeder.accept(grammarAccess.getTerminoAccess().getContextoContextoParserRuleCall_1_0(), semanticObject.getContexto());
		feeder.finish();
	}
	
	
}
