/*
 * generated by Xtext 2.10.0
 */
package org.xtext.tesis.gramatica.serializer;

import com.google.inject.Inject;
import java.util.Set;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.xtext.Action;
import org.eclipse.xtext.Parameter;
import org.eclipse.xtext.ParserRule;
import org.eclipse.xtext.serializer.ISerializationContext;
import org.eclipse.xtext.serializer.acceptor.SequenceFeeder;
import org.eclipse.xtext.serializer.sequencer.AbstractDelegatingSemanticSequencer;
import org.eclipse.xtext.serializer.sequencer.ITransientValueService.ValueTransient;
import org.xtext.tesis.gramatica.gramatica.Atributo;
import org.xtext.tesis.gramatica.gramatica.Clase;
import org.xtext.tesis.gramatica.gramatica.Compleja;
import org.xtext.tesis.gramatica.gramatica.Compuesta;
import org.xtext.tesis.gramatica.gramatica.Determinante;
import org.xtext.tesis.gramatica.gramatica.Documento;
import org.xtext.tesis.gramatica.gramatica.GramaticaPackage;
import org.xtext.tesis.gramatica.gramatica.Negacion;
import org.xtext.tesis.gramatica.gramatica.Nexo;
import org.xtext.tesis.gramatica.gramatica.Obligacion;
import org.xtext.tesis.gramatica.gramatica.ObligacionDeber;
import org.xtext.tesis.gramatica.gramatica.Operacion;
import org.xtext.tesis.gramatica.gramatica.Oracion;
import org.xtext.tesis.gramatica.gramatica.Simple;
import org.xtext.tesis.gramatica.gramatica.SintagmaPreposicional;
import org.xtext.tesis.gramatica.services.GramaticaGrammarAccess;

@SuppressWarnings("all")
public class GramaticaSemanticSequencer extends AbstractDelegatingSemanticSequencer {

	@Inject
	private GramaticaGrammarAccess grammarAccess;
	
	@Override
	public void sequence(ISerializationContext context, EObject semanticObject) {
		EPackage epackage = semanticObject.eClass().getEPackage();
		ParserRule rule = context.getParserRule();
		Action action = context.getAssignedAction();
		Set<Parameter> parameters = context.getEnabledBooleanParameters();
		if (epackage == GramaticaPackage.eINSTANCE)
			switch (semanticObject.eClass().getClassifierID()) {
			case GramaticaPackage.ATRIBUTO:
				sequence_Atributo(context, (Atributo) semanticObject); 
				return; 
			case GramaticaPackage.CLASE:
				sequence_Clase(context, (Clase) semanticObject); 
				return; 
			case GramaticaPackage.COMPLEJA:
				sequence_Compleja(context, (Compleja) semanticObject); 
				return; 
			case GramaticaPackage.COMPUESTA:
				sequence_Compuesta(context, (Compuesta) semanticObject); 
				return; 
			case GramaticaPackage.DETERMINANTE:
				sequence_Determinante(context, (Determinante) semanticObject); 
				return; 
			case GramaticaPackage.DOCUMENTO:
				sequence_Documento(context, (Documento) semanticObject); 
				return; 
			case GramaticaPackage.NEGACION:
				sequence_Negacion(context, (Negacion) semanticObject); 
				return; 
			case GramaticaPackage.NEXO:
				sequence_Nexo(context, (Nexo) semanticObject); 
				return; 
			case GramaticaPackage.OBLIGACION:
				sequence_Obligacion(context, (Obligacion) semanticObject); 
				return; 
			case GramaticaPackage.OBLIGACION_DEBER:
				sequence_ObligacionDeber(context, (ObligacionDeber) semanticObject); 
				return; 
			case GramaticaPackage.OPERACION:
				sequence_Operacion(context, (Operacion) semanticObject); 
				return; 
			case GramaticaPackage.ORACION:
				sequence_Oracion(context, (Oracion) semanticObject); 
				return; 
			case GramaticaPackage.SIMPLE:
				sequence_Simple(context, (Simple) semanticObject); 
				return; 
			case GramaticaPackage.SINTAGMA_PREPOSICIONAL:
				sequence_SintagmaPreposicional(context, (SintagmaPreposicional) semanticObject); 
				return; 
			}
		if (errorAcceptor != null)
			errorAcceptor.accept(diagnosticProvider.createInvalidContextOrTypeDiagnostic(semanticObject, context));
	}
	
	/**
	 * Contexts:
	 *     Atributo returns Atributo
	 *
	 * Constraint:
	 *     name=ID
	 */
	protected void sequence_Atributo(ISerializationContext context, Atributo semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, GramaticaPackage.Literals.ATRIBUTO__NAME) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, GramaticaPackage.Literals.ATRIBUTO__NAME));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getAtributoAccess().getNameIDTerminalRuleCall_1_0(), semanticObject.getName());
		feeder.finish();
	}
	
	
	/**
	 * Contexts:
	 *     Clase returns Clase
	 *
	 * Constraint:
	 *     name=ID
	 */
	protected void sequence_Clase(ISerializationContext context, Clase semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, GramaticaPackage.Literals.CLASE__NAME) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, GramaticaPackage.Literals.CLASE__NAME));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getClaseAccess().getNameIDTerminalRuleCall_0(), semanticObject.getName());
		feeder.finish();
	}
	
	
	/**
	 * Contexts:
	 *     Compleja returns Compleja
	 *
	 * Constraint:
	 *     (
	 *         atributo=Atributo 
	 *         contexto=Clase 
	 *         atributo=Clase 
	 *         (atributo=Atributo (literal=Literal | atributo=Atributo))* 
	 *         (literal=Literal | atributo=Atributo)?
	 *     )
	 */
	protected void sequence_Compleja(ISerializationContext context, Compleja semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Contexts:
	 *     Oracion returns Compuesta
	 *     Compuesta returns Compuesta
	 *
	 * Constraint:
	 *     (simple=Simple nexo=Nexo)
	 */
	protected void sequence_Compuesta(ISerializationContext context, Compuesta semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, GramaticaPackage.Literals.COMPUESTA__SIMPLE) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, GramaticaPackage.Literals.COMPUESTA__SIMPLE));
			if (transientValues.isValueTransient(semanticObject, GramaticaPackage.Literals.COMPUESTA__NEXO) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, GramaticaPackage.Literals.COMPUESTA__NEXO));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getCompuestaAccess().getSimpleSimpleParserRuleCall_0_0(), semanticObject.getSimple());
		feeder.accept(grammarAccess.getCompuestaAccess().getNexoNexoParserRuleCall_1_0(), semanticObject.getNexo());
		feeder.finish();
	}
	
	
	/**
	 * Contexts:
	 *     Determinante returns Determinante
	 *
	 * Constraint:
	 *     (descripcion='El/La' | descripcion='Los/Las')
	 */
	protected void sequence_Determinante(ISerializationContext context, Determinante semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Contexts:
	 *     Documento returns Documento
	 *
	 * Constraint:
	 *     (pathModelo=STRING pathOcl=STRING oraciones+=Oracion*)
	 */
	protected void sequence_Documento(ISerializationContext context, Documento semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Contexts:
	 *     Negacion returns Negacion
	 *
	 * Constraint:
	 *     descripcion='no'
	 */
	protected void sequence_Negacion(ISerializationContext context, Negacion semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, GramaticaPackage.Literals.NEGACION__DESCRIPCION) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, GramaticaPackage.Literals.NEGACION__DESCRIPCION));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getNegacionAccess().getDescripcionNoKeyword_0(), semanticObject.getDescripcion());
		feeder.finish();
	}
	
	
	/**
	 * Contexts:
	 *     Nexo returns Nexo
	 *
	 * Constraint:
	 *     descripcion='y'
	 */
	protected void sequence_Nexo(ISerializationContext context, Nexo semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, GramaticaPackage.Literals.NEXO__DESCRIPCION) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, GramaticaPackage.Literals.NEXO__DESCRIPCION));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getNexoAccess().getDescripcionYKeyword_0_0(), semanticObject.getDescripcion());
		feeder.finish();
	}
	
	
	/**
	 * Contexts:
	 *     ObligacionDeber returns ObligacionDeber
	 *
	 * Constraint:
	 *     (descripcion='debe ser' | descripcion='debe estar')
	 */
	protected void sequence_ObligacionDeber(ISerializationContext context, ObligacionDeber semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Contexts:
	 *     Obligacion returns Obligacion
	 *
	 * Constraint:
	 *     (negacion=Negacion? obligacionDeber=ObligacionDeber)
	 */
	protected void sequence_Obligacion(ISerializationContext context, Obligacion semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Contexts:
	 *     Operacion returns Operacion
	 *
	 * Constraint:
	 *     (
	 *         descripcion='mayor que' | 
	 *         descripcion='menor que' | 
	 *         descripcion='igual a' | 
	 *         descripcion='mayor o igual a' | 
	 *         descripcion='menor o igual a' | 
	 *         descripcion='distinto de' | 
	 *         descripcion='al menos'
	 *     )
	 */
	protected void sequence_Operacion(ISerializationContext context, Operacion semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Contexts:
	 *     Oracion returns Oracion
	 *
	 * Constraint:
	 *     contenido=Simple
	 */
	protected void sequence_Oracion(ISerializationContext context, Oracion semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, GramaticaPackage.Literals.ORACION__CONTENIDO) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, GramaticaPackage.Literals.ORACION__CONTENIDO));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getOracionAccess().getContenidoSimpleParserRuleCall_0_0(), semanticObject.getContenido());
		feeder.finish();
	}
	
	
	/**
	 * Contexts:
	 *     Simple returns Simple
	 *
	 * Constraint:
	 *     (
	 *         determinante=Determinante 
	 *         atributo=Atributo 
	 *         Sintagma=SintagmaPreposicional 
	 *         contexto=Clase 
	 *         obligacion=Obligacion 
	 *         operacion=Operacion? 
	 *         (literal=Literal | atributo=Atributo) 
	 *         finOracion=FinOracion?
	 *     )
	 */
	protected void sequence_Simple(ISerializationContext context, Simple semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Contexts:
	 *     SintagmaPreposicional returns SintagmaPreposicional
	 *
	 * Constraint:
	 *     descripcion='de un/una'
	 */
	protected void sequence_SintagmaPreposicional(ISerializationContext context, SintagmaPreposicional semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, GramaticaPackage.Literals.SINTAGMA_PREPOSICIONAL__DESCRIPCION) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, GramaticaPackage.Literals.SINTAGMA_PREPOSICIONAL__DESCRIPCION));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getSintagmaPreposicionalAccess().getDescripcionDeUnUnaKeyword_0(), semanticObject.getDescripcion());
		feeder.finish();
	}
	
	
}
