/*
 * generated by Xtext 2.10.0-SNAPSHOT
 */
package org.xtext.example.lenguajenaturalreducido.services;

import com.google.inject.Inject;
import com.google.inject.Singleton;
import java.util.List;
import org.eclipse.xtext.Alternatives;
import org.eclipse.xtext.Assignment;
import org.eclipse.xtext.Grammar;
import org.eclipse.xtext.GrammarUtil;
import org.eclipse.xtext.Group;
import org.eclipse.xtext.Keyword;
import org.eclipse.xtext.ParserRule;
import org.eclipse.xtext.RuleCall;
import org.eclipse.xtext.TerminalRule;
import org.eclipse.xtext.common.services.TerminalsGrammarAccess;
import org.eclipse.xtext.service.AbstractElementFinder.AbstractGrammarElementFinder;
import org.eclipse.xtext.service.GrammarProvider;

@Singleton
public class LenguajeNaturalReducidoGrammarAccess extends AbstractGrammarElementFinder {
	
	public class DocumentoElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.lenguajenaturalreducido.LenguajeNaturalReducido.Documento");
		private final Assignment cOracionesAssignment = (Assignment)rule.eContents().get(1);
		private final RuleCall cOracionesOracionParserRuleCall_0 = (RuleCall)cOracionesAssignment.eContents().get(0);
		
		//Documento:
		//	oraciones+=Oracion*;
		@Override public ParserRule getRule() { return rule; }
		
		//oraciones+=Oracion*
		public Assignment getOracionesAssignment() { return cOracionesAssignment; }
		
		//Oracion
		public RuleCall getOracionesOracionParserRuleCall_0() { return cOracionesOracionParserRuleCall_0; }
	}
	public class OracionElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.lenguajenaturalreducido.LenguajeNaturalReducido.Oracion");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cOracionAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final Alternatives cOracionAlternatives_0_0 = (Alternatives)cOracionAssignment_0.eContents().get(0);
		private final RuleCall cOracionSimpleParserRuleCall_0_0_0 = (RuleCall)cOracionAlternatives_0_0.eContents().get(0);
		private final RuleCall cOracionCompuestaParserRuleCall_0_0_1 = (RuleCall)cOracionAlternatives_0_0.eContents().get(1);
		private final RuleCall cFinOracionParserRuleCall_1 = (RuleCall)cGroup.eContents().get(1);
		
		//Oracion:
		//	oracion=(Simple | Compuesta) FinOracion;
		@Override public ParserRule getRule() { return rule; }
		
		//oracion=(Simple | Compuesta) FinOracion
		public Group getGroup() { return cGroup; }
		
		//oracion=(Simple | Compuesta)
		public Assignment getOracionAssignment_0() { return cOracionAssignment_0; }
		
		//(Simple | Compuesta)
		public Alternatives getOracionAlternatives_0_0() { return cOracionAlternatives_0_0; }
		
		//Simple
		public RuleCall getOracionSimpleParserRuleCall_0_0_0() { return cOracionSimpleParserRuleCall_0_0_0; }
		
		//Compuesta
		public RuleCall getOracionCompuestaParserRuleCall_0_0_1() { return cOracionCompuestaParserRuleCall_0_0_1; }
		
		//FinOracion
		public RuleCall getFinOracionParserRuleCall_1() { return cFinOracionParserRuleCall_1; }
	}
	public class FinOracionElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.lenguajenaturalreducido.LenguajeNaturalReducido.FinOracion");
		private final Keyword cFullStopControl000dControl000aKeyword = (Keyword)rule.eContents().get(1);
		
		//FinOracion:
		//	'.\r\n';
		@Override public ParserRule getRule() { return rule; }
		
		//'.\r\n'
		public Keyword getFullStopControl000dControl000aKeyword() { return cFullStopControl000dControl000aKeyword; }
	}
	public class CompuestaElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.lenguajenaturalreducido.LenguajeNaturalReducido.Compuesta");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final RuleCall cSimpleParserRuleCall_0 = (RuleCall)cGroup.eContents().get(0);
		private final Group cGroup_1 = (Group)cGroup.eContents().get(1);
		private final RuleCall cNexoParserRuleCall_1_0 = (RuleCall)cGroup_1.eContents().get(0);
		private final RuleCall cSimpleParserRuleCall_1_1 = (RuleCall)cGroup_1.eContents().get(1);
		
		//Compuesta:
		//	Simple (Nexo Simple)+;
		@Override public ParserRule getRule() { return rule; }
		
		//Simple (Nexo Simple)+
		public Group getGroup() { return cGroup; }
		
		//Simple
		public RuleCall getSimpleParserRuleCall_0() { return cSimpleParserRuleCall_0; }
		
		//(Nexo Simple)+
		public Group getGroup_1() { return cGroup_1; }
		
		//Nexo
		public RuleCall getNexoParserRuleCall_1_0() { return cNexoParserRuleCall_1_0; }
		
		//Simple
		public RuleCall getSimpleParserRuleCall_1_1() { return cSimpleParserRuleCall_1_1; }
	}
	public class NexoElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.lenguajenaturalreducido.LenguajeNaturalReducido.Nexo");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final Keyword cYKeyword_0 = (Keyword)cAlternatives.eContents().get(0);
		private final Keyword cOKeyword_1 = (Keyword)cAlternatives.eContents().get(1);
		private final Keyword cEntoncesKeyword_2 = (Keyword)cAlternatives.eContents().get(2);
		
		//Nexo:
		//	'y' | 'o' | 'entonces';
		@Override public ParserRule getRule() { return rule; }
		
		//'y' | 'o' | 'entonces'
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//'y'
		public Keyword getYKeyword_0() { return cYKeyword_0; }
		
		//'o'
		public Keyword getOKeyword_1() { return cOKeyword_1; }
		
		//'entonces'
		public Keyword getEntoncesKeyword_2() { return cEntoncesKeyword_2; }
	}
	public class SimpleElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.lenguajenaturalreducido.LenguajeNaturalReducido.Simple");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final RuleCall cDeterminanteParserRuleCall_0 = (RuleCall)cGroup.eContents().get(0);
		private final RuleCall cAtributoParserRuleCall_1 = (RuleCall)cGroup.eContents().get(1);
		private final RuleCall cSintagmaPreposicionalParserRuleCall_2 = (RuleCall)cGroup.eContents().get(2);
		private final RuleCall cObligacionParserRuleCall_3 = (RuleCall)cGroup.eContents().get(3);
		private final RuleCall cOperacionParserRuleCall_4 = (RuleCall)cGroup.eContents().get(4);
		private final Alternatives cAlternatives_5 = (Alternatives)cGroup.eContents().get(5);
		private final RuleCall cLiteralParserRuleCall_5_0 = (RuleCall)cAlternatives_5.eContents().get(0);
		private final RuleCall cAtributoParserRuleCall_5_1 = (RuleCall)cAlternatives_5.eContents().get(1);
		
		//Simple:
		//	Determinante Atributo SintagmaPreposicional Obligacion Operacion (Literal | Atributo);
		@Override public ParserRule getRule() { return rule; }
		
		//Determinante Atributo SintagmaPreposicional Obligacion Operacion (Literal | Atributo)
		public Group getGroup() { return cGroup; }
		
		//Determinante
		public RuleCall getDeterminanteParserRuleCall_0() { return cDeterminanteParserRuleCall_0; }
		
		//Atributo
		public RuleCall getAtributoParserRuleCall_1() { return cAtributoParserRuleCall_1; }
		
		//SintagmaPreposicional
		public RuleCall getSintagmaPreposicionalParserRuleCall_2() { return cSintagmaPreposicionalParserRuleCall_2; }
		
		//Obligacion
		public RuleCall getObligacionParserRuleCall_3() { return cObligacionParserRuleCall_3; }
		
		//Operacion
		public RuleCall getOperacionParserRuleCall_4() { return cOperacionParserRuleCall_4; }
		
		//(Literal | Atributo)
		public Alternatives getAlternatives_5() { return cAlternatives_5; }
		
		//Literal
		public RuleCall getLiteralParserRuleCall_5_0() { return cLiteralParserRuleCall_5_0; }
		
		//Atributo
		public RuleCall getAtributoParserRuleCall_5_1() { return cAtributoParserRuleCall_5_1; }
	}
	public class DeterminanteElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.lenguajenaturalreducido.LenguajeNaturalReducido.Determinante");
		private final Keyword cElLaKeyword = (Keyword)rule.eContents().get(1);
		
		//Determinante:
		//	'El/La';
		@Override public ParserRule getRule() { return rule; }
		
		//'El/La'
		public Keyword getElLaKeyword() { return cElLaKeyword; }
	}
	public class SintagmaPreposicionalElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.lenguajenaturalreducido.LenguajeNaturalReducido.SintagmaPreposicional");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final RuleCall cEnlaceParserRuleCall_0 = (RuleCall)cGroup.eContents().get(0);
		private final RuleCall cTerminoParserRuleCall_1 = (RuleCall)cGroup.eContents().get(1);
		
		//SintagmaPreposicional:
		//	Enlace Termino;
		@Override public ParserRule getRule() { return rule; }
		
		//Enlace Termino
		public Group getGroup() { return cGroup; }
		
		//Enlace
		public RuleCall getEnlaceParserRuleCall_0() { return cEnlaceParserRuleCall_0; }
		
		//Termino
		public RuleCall getTerminoParserRuleCall_1() { return cTerminoParserRuleCall_1; }
	}
	public class EnlaceElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.lenguajenaturalreducido.LenguajeNaturalReducido.Enlace");
		private final Keyword cDeKeyword = (Keyword)rule.eContents().get(1);
		
		//Enlace:
		//	'de';
		@Override public ParserRule getRule() { return rule; }
		
		//'de'
		public Keyword getDeKeyword() { return cDeKeyword; }
	}
	public class TerminoElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.lenguajenaturalreducido.LenguajeNaturalReducido.Termino");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final RuleCall cIndeterminanteParserRuleCall_0 = (RuleCall)cGroup.eContents().get(0);
		private final RuleCall cClaseParserRuleCall_1 = (RuleCall)cGroup.eContents().get(1);
		
		//Termino:
		//	Indeterminante Clase;
		@Override public ParserRule getRule() { return rule; }
		
		//Indeterminante Clase
		public Group getGroup() { return cGroup; }
		
		//Indeterminante
		public RuleCall getIndeterminanteParserRuleCall_0() { return cIndeterminanteParserRuleCall_0; }
		
		//Clase
		public RuleCall getClaseParserRuleCall_1() { return cClaseParserRuleCall_1; }
	}
	public class IndeterminanteElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.lenguajenaturalreducido.LenguajeNaturalReducido.Indeterminante");
		private final Keyword cUnUnaKeyword = (Keyword)rule.eContents().get(1);
		
		//Indeterminante:
		//	'un/una';
		@Override public ParserRule getRule() { return rule; }
		
		//'un/una'
		public Keyword getUnUnaKeyword() { return cUnUnaKeyword; }
	}
	public class ObligacionElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.lenguajenaturalreducido.LenguajeNaturalReducido.Obligacion");
		private final Keyword cDebeSerKeyword = (Keyword)rule.eContents().get(1);
		
		//Obligacion:
		//	'debe ser';
		@Override public ParserRule getRule() { return rule; }
		
		//'debe ser'
		public Keyword getDebeSerKeyword() { return cDebeSerKeyword; }
	}
	public class OperacionElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.lenguajenaturalreducido.LenguajeNaturalReducido.Operacion");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final Keyword cMayorQueKeyword_0 = (Keyword)cAlternatives.eContents().get(0);
		private final Keyword cMenorQueKeyword_1 = (Keyword)cAlternatives.eContents().get(1);
		private final Keyword cIgualAKeyword_2 = (Keyword)cAlternatives.eContents().get(2);
		private final Keyword cMayorOIgualAKeyword_3 = (Keyword)cAlternatives.eContents().get(3);
		private final Keyword cMenorOIgualAKeyword_4 = (Keyword)cAlternatives.eContents().get(4);
		private final Keyword cDistintoDeKeyword_5 = (Keyword)cAlternatives.eContents().get(5);
		
		/// *Mejorar nombre por algo mas singnificativo * / Operacion:
		//	'mayor que' | 'menor que' | 'igual a' | 'mayor o igual a' | 'menor o igual a' | 'distinto de';
		@Override public ParserRule getRule() { return rule; }
		
		//'mayor que' | 'menor que' | 'igual a' | 'mayor o igual a' | 'menor o igual a' | 'distinto de'
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//'mayor que'
		public Keyword getMayorQueKeyword_0() { return cMayorQueKeyword_0; }
		
		//'menor que'
		public Keyword getMenorQueKeyword_1() { return cMenorQueKeyword_1; }
		
		//'igual a'
		public Keyword getIgualAKeyword_2() { return cIgualAKeyword_2; }
		
		//'mayor o igual a'
		public Keyword getMayorOIgualAKeyword_3() { return cMayorOIgualAKeyword_3; }
		
		//'menor o igual a'
		public Keyword getMenorOIgualAKeyword_4() { return cMenorOIgualAKeyword_4; }
		
		//'distinto de'
		public Keyword getDistintoDeKeyword_5() { return cDistintoDeKeyword_5; }
	}
	public class LiteralElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.lenguajenaturalreducido.LenguajeNaturalReducido.Literal");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cINTTerminalRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cSTRINGTerminalRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		
		/// *Mejorar nombre* / Literal:
		//	INT | STRING;
		@Override public ParserRule getRule() { return rule; }
		
		//INT | STRING
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//INT
		public RuleCall getINTTerminalRuleCall_0() { return cINTTerminalRuleCall_0; }
		
		//STRING
		public RuleCall getSTRINGTerminalRuleCall_1() { return cSTRINGTerminalRuleCall_1; }
	}
	public class AtributoElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.lenguajenaturalreducido.LenguajeNaturalReducido.Atributo");
		private final RuleCall cIDTerminalRuleCall = (RuleCall)rule.eContents().get(1);
		
		//Atributo:
		//	ID;
		@Override public ParserRule getRule() { return rule; }
		
		//ID
		public RuleCall getIDTerminalRuleCall() { return cIDTerminalRuleCall; }
	}
	public class ClaseElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.lenguajenaturalreducido.LenguajeNaturalReducido.Clase");
		private final RuleCall cIDTerminalRuleCall = (RuleCall)rule.eContents().get(1);
		
		//Clase:
		//	ID;
		@Override public ParserRule getRule() { return rule; }
		
		//ID
		public RuleCall getIDTerminalRuleCall() { return cIDTerminalRuleCall; }
	}
	
	
	private final DocumentoElements pDocumento;
	private final OracionElements pOracion;
	private final FinOracionElements pFinOracion;
	private final CompuestaElements pCompuesta;
	private final NexoElements pNexo;
	private final SimpleElements pSimple;
	private final DeterminanteElements pDeterminante;
	private final SintagmaPreposicionalElements pSintagmaPreposicional;
	private final EnlaceElements pEnlace;
	private final TerminoElements pTermino;
	private final IndeterminanteElements pIndeterminante;
	private final ObligacionElements pObligacion;
	private final OperacionElements pOperacion;
	private final LiteralElements pLiteral;
	private final AtributoElements pAtributo;
	private final ClaseElements pClase;
	
	private final Grammar grammar;
	
	private final TerminalsGrammarAccess gaTerminals;

	@Inject
	public LenguajeNaturalReducidoGrammarAccess(GrammarProvider grammarProvider,
			TerminalsGrammarAccess gaTerminals) {
		this.grammar = internalFindGrammar(grammarProvider);
		this.gaTerminals = gaTerminals;
		this.pDocumento = new DocumentoElements();
		this.pOracion = new OracionElements();
		this.pFinOracion = new FinOracionElements();
		this.pCompuesta = new CompuestaElements();
		this.pNexo = new NexoElements();
		this.pSimple = new SimpleElements();
		this.pDeterminante = new DeterminanteElements();
		this.pSintagmaPreposicional = new SintagmaPreposicionalElements();
		this.pEnlace = new EnlaceElements();
		this.pTermino = new TerminoElements();
		this.pIndeterminante = new IndeterminanteElements();
		this.pObligacion = new ObligacionElements();
		this.pOperacion = new OperacionElements();
		this.pLiteral = new LiteralElements();
		this.pAtributo = new AtributoElements();
		this.pClase = new ClaseElements();
	}
	
	protected Grammar internalFindGrammar(GrammarProvider grammarProvider) {
		Grammar grammar = grammarProvider.getGrammar(this);
		while (grammar != null) {
			if ("org.xtext.example.lenguajenaturalreducido.LenguajeNaturalReducido".equals(grammar.getName())) {
				return grammar;
			}
			List<Grammar> grammars = grammar.getUsedGrammars();
			if (!grammars.isEmpty()) {
				grammar = grammars.iterator().next();
			} else {
				return null;
			}
		}
		return grammar;
	}
	
	@Override
	public Grammar getGrammar() {
		return grammar;
	}
	
	
	public TerminalsGrammarAccess getTerminalsGrammarAccess() {
		return gaTerminals;
	}

	
	//Documento:
	//	oraciones+=Oracion*;
	public DocumentoElements getDocumentoAccess() {
		return pDocumento;
	}
	
	public ParserRule getDocumentoRule() {
		return getDocumentoAccess().getRule();
	}
	
	//Oracion:
	//	oracion=(Simple | Compuesta) FinOracion;
	public OracionElements getOracionAccess() {
		return pOracion;
	}
	
	public ParserRule getOracionRule() {
		return getOracionAccess().getRule();
	}
	
	//FinOracion:
	//	'.\r\n';
	public FinOracionElements getFinOracionAccess() {
		return pFinOracion;
	}
	
	public ParserRule getFinOracionRule() {
		return getFinOracionAccess().getRule();
	}
	
	//Compuesta:
	//	Simple (Nexo Simple)+;
	public CompuestaElements getCompuestaAccess() {
		return pCompuesta;
	}
	
	public ParserRule getCompuestaRule() {
		return getCompuestaAccess().getRule();
	}
	
	//Nexo:
	//	'y' | 'o' | 'entonces';
	public NexoElements getNexoAccess() {
		return pNexo;
	}
	
	public ParserRule getNexoRule() {
		return getNexoAccess().getRule();
	}
	
	//Simple:
	//	Determinante Atributo SintagmaPreposicional Obligacion Operacion (Literal | Atributo);
	public SimpleElements getSimpleAccess() {
		return pSimple;
	}
	
	public ParserRule getSimpleRule() {
		return getSimpleAccess().getRule();
	}
	
	//Determinante:
	//	'El/La';
	public DeterminanteElements getDeterminanteAccess() {
		return pDeterminante;
	}
	
	public ParserRule getDeterminanteRule() {
		return getDeterminanteAccess().getRule();
	}
	
	//SintagmaPreposicional:
	//	Enlace Termino;
	public SintagmaPreposicionalElements getSintagmaPreposicionalAccess() {
		return pSintagmaPreposicional;
	}
	
	public ParserRule getSintagmaPreposicionalRule() {
		return getSintagmaPreposicionalAccess().getRule();
	}
	
	//Enlace:
	//	'de';
	public EnlaceElements getEnlaceAccess() {
		return pEnlace;
	}
	
	public ParserRule getEnlaceRule() {
		return getEnlaceAccess().getRule();
	}
	
	//Termino:
	//	Indeterminante Clase;
	public TerminoElements getTerminoAccess() {
		return pTermino;
	}
	
	public ParserRule getTerminoRule() {
		return getTerminoAccess().getRule();
	}
	
	//Indeterminante:
	//	'un/una';
	public IndeterminanteElements getIndeterminanteAccess() {
		return pIndeterminante;
	}
	
	public ParserRule getIndeterminanteRule() {
		return getIndeterminanteAccess().getRule();
	}
	
	//Obligacion:
	//	'debe ser';
	public ObligacionElements getObligacionAccess() {
		return pObligacion;
	}
	
	public ParserRule getObligacionRule() {
		return getObligacionAccess().getRule();
	}
	
	/// *Mejorar nombre por algo mas singnificativo * / Operacion:
	//	'mayor que' | 'menor que' | 'igual a' | 'mayor o igual a' | 'menor o igual a' | 'distinto de';
	public OperacionElements getOperacionAccess() {
		return pOperacion;
	}
	
	public ParserRule getOperacionRule() {
		return getOperacionAccess().getRule();
	}
	
	/// *Mejorar nombre* / Literal:
	//	INT | STRING;
	public LiteralElements getLiteralAccess() {
		return pLiteral;
	}
	
	public ParserRule getLiteralRule() {
		return getLiteralAccess().getRule();
	}
	
	//Atributo:
	//	ID;
	public AtributoElements getAtributoAccess() {
		return pAtributo;
	}
	
	public ParserRule getAtributoRule() {
		return getAtributoAccess().getRule();
	}
	
	//Clase:
	//	ID;
	public ClaseElements getClaseAccess() {
		return pClase;
	}
	
	public ParserRule getClaseRule() {
		return getClaseAccess().getRule();
	}
	
	//terminal ID:
	//	'^'? ('a'..'z' | 'A'..'Z' | '_') ('a'..'z' | 'A'..'Z' | '_' | '0'..'9')*;
	public TerminalRule getIDRule() {
		return gaTerminals.getIDRule();
	}
	
	//terminal INT returns ecore::EInt:
	//	'0'..'9'+;
	public TerminalRule getINTRule() {
		return gaTerminals.getINTRule();
	}
	
	//terminal STRING:
	//	'"' ('\\' . | !('\\' | '"'))* '"' | "'" ('\\' . | !('\\' | "'"))* "'";
	public TerminalRule getSTRINGRule() {
		return gaTerminals.getSTRINGRule();
	}
	
	//terminal ML_COMMENT:
	//	'/ *'->'* /';
	public TerminalRule getML_COMMENTRule() {
		return gaTerminals.getML_COMMENTRule();
	}
	
	//terminal SL_COMMENT:
	//	'//' !('\n' | '\r')* ('\r'? '\n')?;
	public TerminalRule getSL_COMMENTRule() {
		return gaTerminals.getSL_COMMENTRule();
	}
	
	//terminal WS:
	//	' ' | '\t' | '\r' | '\n'+;
	public TerminalRule getWSRule() {
		return gaTerminals.getWSRule();
	}
	
	//terminal ANY_OTHER:
	//	.;
	public TerminalRule getANY_OTHERRule() {
		return gaTerminals.getANY_OTHERRule();
	}
}
