<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="ejemploTesina" nsURI="http://www.example.org/ejemploTesina"
    nsPrefix="ejemploTesina">
  <eClassifiers xsi:type="ecore:EClass" name="Banco"/>
  <eClassifiers xsi:type="ecore:EClass" name="Persona">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="nombre" ordered="false"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="apellido" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="edad" ordered="false" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="estaCasada" ordered="false"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBooleanObject"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="estaDesocupada" ordered="false"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBooleanObject"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="fechaDeNacimiento" ordered="false"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="genero" ordered="false"
        eType="#//Genero"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="matrimonios" ordered="false"
        unique="false" upperBound="-1" eType="#//Matrimonio" resolveProxies="false">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="administra" upperBound="-1"
        eType="#//Compañia"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="posiciones" ordered="false"
        unique="false" upperBound="-1" eType="#//Posicion" eOpposite="#//Posicion/persona"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Matrimonio">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="lugar" ordered="false"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="fechaDeMatrimonio" ordered="false"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="fechaDeDivorcio" ordered="false"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="esposo" eType="#//Persona"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="esposa" eType="#//Persona"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="Genero">
    <eLiterals name="Femenino"/>
    <eLiterals name="Masculino"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Compañia">
    <eOperations name="precioDeLaAccion" ordered="false" unique="false"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" ordered="false" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="cantidadDeEmpleados" ordered="false"
        unique="false" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="administrador" ordered="false"
        unique="false" eType="#//Persona"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="posiciones" upperBound="-1"
        eType="#//Posicion"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Posicion">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="titulo" ordered="false"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="sueldo" ordered="false"
        unique="false" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="fechaDeComienzo" ordered="false"
        unique="false" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="persona" eType="#//Persona"
        eOpposite="#//Persona/posiciones"/>
  </eClassifiers>
</ecore:EPackage>
